### ISSUE TITLE
Parameters, causes and troubleshooting

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1119]
Add parameters description, possible causes and troubleshooting steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64521c99-6b84-0b52-ef96-efccf3b46d0a
* Version Independent ID: 418df85d-a861-a2ed-29f8-6d37d8bc1b1d
* Content: [Bug Check 0x18B SECURE_KERNEL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x18b--secure-kernel-error)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x18b--secure-kernel-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x18b--secure-kernel-error.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Thanks for this issue. Because we have not documented information on this bug check before, I would need to check with the dev team to be able to do that. As I have mentioned before, we use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes. 

Right now I'm working on the new stop codes that we have not documented at all.

Thank you for your interest in improving our stop code docs.

**Comment by tinus-github** [comment]
Note that this kind of non-documentation is worse than useless. If you don’t have resources to add documentation for 100s of defined bug checks, don’t define 100s of bug checks.

**Comment by DOMARS** [comment]
@LuigiBruno - I have opened an internal work item to track this work, so closing this issue for now.

As I have mentioned before, we use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes.

Thank you for your interest in improving our stop code docs.
