### ISSUE TITLE
Bug check 0x139 parameter 1 0x3b

### ISSUE THREAD

**Issue by coaledwarrior** [MicrosoftDocs/windows-driver-docs#1140]
Would it be possible to update the list of parameter 1 for bug check 0x139 to include 0x3b (present on the fast-ring Windows build)?

**Comment by DOMARS** [comment]
@coaledwarrior - Thanks for this PR. Because we have not documented information on this bug check before, I would need to check with the dev team to be able to do that. We use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, this process will likely take a while.

**Comment by DOMARS** [comment]
@coaledwarrior - I checked with the dev team and these additional codes are for Windows internal use, so I will not be able to document them. Thanks for passing on the parameter 1 value that you encountered  and thanks for your interest in improving the stop code documentation.
