### ISSUE TITLE
CHID targetting

### ISSUE THREAD

**Issue by CKroid** [MicrosoftDocs/windows-driver-docs#1214]
For a shipping label, if we targetting all our hardware IDs and do not specify CHID, all our hardware will be able to get the WU.
However, once we add one CHID, only that machine will be able to get the WU and all other will not be able to get.
Is there a way to specify specific CHID to opt out of the WU instead of opt in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 531ef6ee-7a29-e6d0-56d6-e08a923b0aa4
* Version Independent ID: d00f4b65-2ae6-643f-d67a-c04f916a7058
* Content: [Publish a driver to Windows Update - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/publish-a-driver-to-windows-update)
* Content Source: [windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @CKroid.
The short answer to your question is, No.
The current design is our expected behavior.  Adding a CHID reduces the WU scope to only those systems having that CHID.    In order to solve this, you would create a new shipping label in the submission where the driver version is correct for that CHID, and add that single CHID to that new shipping label. For example,
•	CHID- xxxxxx  needs to stay on driver version 2.0.0.        
•	Driver 2.0.0 is in SubmissionID 1234
•	Shipping Label for driver version 3.0.0 includes all HWIDs and no CHID.  <problem—it shouldn’t go to systems with CHID xxxxx>
•	Solution:  Create a new Shipping label under SubmissionID 1234 for Driver 2.0.0 that includes the CHIDs to be held back.      
 
Let me know if you need further clarity. And thanks so much for the Issue.
