### ISSUE TITLE
Less 32-bit centric, more symbol usage

### ISSUE THREAD

**Issue by bendono** [MicrosoftDocs/windows-driver-docs#1220]
This is a useful document. However, it could be better.
1) It is very 32-bit centric. It should also 64-bit, or better, be less bit-centric.
2) "If you had complete symbols, you could use dt TEB to do this." Symbols are publicly available, so there should at least be some discuss about options with symbols. Should mention that StackBase, StackLimit, and DeallocationStack are available via @$teb-&gt;NtTib.StackBase, @$teb-&gt;StackLimit, and @$teb-&gt;DeallocationStack respectively. Further, the statements below can used to extract desired information:
  * Stack size: ?? int(@$teb-&gt;NtTib.StackBase) - int(@$teb-&gt;NtTib.StackLimit)
  * Maximum stack size: ?? int(@$teb-&gt;NtTib.StackBase) - int(@$teb-&gt;DeallocationStack)

3) "dd 7ffdc000 L4" Since we are looking for addresses, dp &lt;address&gt; L3 is more appropriate. It will also work fine on 64-bit architectures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542fe7f0-0b5d-3567-7a8f-68fba68573f8
* Version Independent ID: f2074fa7-134c-d9a3-79aa-21d726b28199
* Content: [Debugging a Stack Overflow - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-a-stack-overflow)
* Content Source: [windows-driver-docs-pr/debugger/debugging-a-stack-overflow.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-a-stack-overflow.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@bendono - I see the value of updating this topic to 64 bit, but as the topic is currently correct, and illustrates the general workflow, it will be difficult to schedule that work for this enhancement. On the symbols, I also see how you could add additional commands to show how to take advantage of public symbols, when those are available. There are advantages to seeing how to work with out symbols, so that technique shown here, has some value. If you would like to create a PR with this work, I would be happy to review this. We aggregate input like this to help determine our priorities, so I appreciate the interest in the debugger how to topics.
