### ISSUE TITLE
Please give  the download link

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1242]
Sir  please  give  download link which contains only GPUView.zip files, so that users can download separately and add  to  C:\windows\system32\.
Include  both  32bit and 64bit versions 
Thanks to authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5371abe0-588e-75e0-caab-96fe3b8f275a
* Version Independent ID: 06f1f66e-6d3b-dcaa-548f-dffae63faf18
* Content: [Using GPUView - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/using-gpuview)
* Content Source: [windows-driver-docs-pr/display/using-gpuview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/using-gpuview.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Thanks for pointing this out! It helps with doc improvements. For more information about GPUView and how to enable it, see https://graphics.stanford.edu/~mdfisher/GPUView.html 
I will include a link to the article from this topic.

**Comment by giblet37** [comment]
I'm not sure if things have changed, but that link does not help - it simply refers back to the same MS Docs page for the download.  Trying to install the entire Win7 SDK just for a single executable tool seems excessive (not to mention that the install keeps failing...)

Providing a link to the actual tool, rather than directing us in a circular reference, would be much more helpful!
