### ISSUE TITLE
NDIS interface provider providing NDIS interface services...

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#1362]
The words "interface" and "provider" and "service" are used so frequently in any given sentence that it becomes difficult to tease out the specific meaning, at least to someone trying to become familiar with the material. "NDIS" and "NDISIF" and "NDIS IF" may also appear multiple times in a sentence. Maybe it's just me, but it seems like this page could benefit from a writer armed with a thesaurus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e565aa-dbbf-2662-b638-ff1b9242de81
* Version Independent ID: e0449c99-60ca-4894-bb70-8d41cd231e0f
* Content: [NDIS Network Interface Architecture - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-network-interface-architecture)
* Content Source: [windows-driver-docs-pr/network/ndis-network-interface-architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/ndis-network-interface-architecture.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @druske, thanks for the feedback. I can see how this might be a bit confusing for someone learning the material, so I've made some minor style and organizational changes to help emphasize clearer meaning Unfortunately, I can't change the wording too much since the definitions are what they are, but hopefully this helps. Those changes should be live later today, Redmond time.

If you're new to NDIS and network drivers in general, I'd suggest starting with the [Roadmap for Developing NDISDrivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/roadmap-for-developing-ndis-drivers) which should help you acclimate to general terminology and ideas. In addition, the pages surrounding this one in the table of contents should help clarify exactly what NDIS network interface providers are and what they do (all the pages under the [NDIS Network Interfaces](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-network-interfaces2) doc node).

If you have specific suggestions for how to clarify the content, you're more than welcome to edit the page and submit a PR that I can then review and merge for you. Thanks!
