### ISSUE TITLE
WDM or WDF?

### ISSUE THREAD

**Issue by piotrbocian** [MicrosoftDocs/windows-driver-docs#1442]
Is WDF based Crash Dump Filter Driver supported? From debug I can see that WDF based driver crashes on FxDriverEntry, before DriverEntry being called.

```
03 ffffe383`a3c06020 fffff806`183d474f nt!KeBugCheckEx+0x107
04 ffffe383`a3c06060 fffff806`1839741f nt!PspSystemThreadStartup$filt$0+0x44
05 ffffe383`a3c060a0 fffff806`183c50cf nt!_C_specific_handler+0x9f
06 ffffe383`a3c06110 fffff806`1822fb20 nt!RtlpExecuteHandlerForException+0xf
07 ffffe383`a3c06140 fffff806`18274e74 nt!RtlDispatchException+0x430
08 ffffe383`a3c06890 fffff806`183cde42 nt!KiDispatchException+0x144
09 ffffe383`a3c06f40 fffff806`183ca168 nt!KiExceptionDispatch+0xc2
0a ffffe383`a3c07120 fffff806`183cee20 nt!KiPageFault+0x428
0b ffffe383`a3c072b8 fffff806`182c2eb3 nt!memcpy+0x1e0
0c ffffe383`a3c072c0 fffff806`2fb93293 nt!RtlCopyUnicodeString+0x43
0d ffffe383`a3c072f0 fffff808`8b5e1431 dump_MY_FILTER!FxDriverEntryWorker+0x57 
0e ffffe383`a3c07320 fffff808`8b5e130e crashdmp!FilterCallback+0x111
0f ffffe383`a3c07380 fffff808`8b5f2cfe crashdmp!InitializeFilterDrivers+0xe
10 ffffe383`a3c073b0 fffff808`8b5f28ec crashdmp!CrashdmpLoadDumpStack+0x1be
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ee2a9b-4f66-0249-0905-4300663e68ab
* Version Independent ID: 7f1e8031-000d-07cf-2494-24eda04795ca
* Content: [Crash Dump Filter Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/crash-dump-filter-drivers)
* Content Source: [windows-driver-docs-pr/storage/crash-dump-filter-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/crash-dump-filter-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@piotrbocian , I reached out to the WDF dev team and got the following response. Hope this info helps (although I'm guessing you've already figured this out since you hit the issue in April - sorry for the slow response).

"The standard NT kernel driver, for which WDF provides support, exports a DriverEntry callback with a DriverObject and RegistryPath parameters. However, this crash dump filter driver does not use such parameters at all. Thus it is not supported by WDF."

Supporting documentation that they thought might benefit you is here:

[https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/feature-description](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/feature-description)
The crash dump driver provides a new interface to add filter drivers to the crash dump stack. This interface does not follow any standard filter driver model. Instead, it exposes a proprietary interface that must be used in order to load a driver into the crash dump stack.

[https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/filter-initialization]((https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/filter-initialization))
When the filter driver is called, DriverObject points to a FILTER_EXTENSION structure, and RegistryPath points to a FILTER_INITIALIZATION_DATA structure.

So your crash dump would look something like this:
dump_my_filter!DriverEntry
crashdmp!FilterCallback+0x111
crashdmp!InitializeFilterDrivers+0xe
crashdmp!CrashdmpLoadDumpStack+0x1be
