### ISSUE TITLE
Requesting filter option

### ISSUE THREAD

**Issue by moolwalk** [MicrosoftDocs/windows-driver-docs#1517]
Since getting all products results in huge amount of the items, why don't we have a filtering feature by querying like 

~/v1.0/my/hardware/products/?$filter=productName eq ContosoGraphics

I was recently inspired by OData query option in the link below.

- Supporting OData Query Options in ASP.NET Web API 2
https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options 

MSFT could make use of the feature above to extend the GetProductData query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c20769b-d969-a51a-4eb3-f9cc27875f28
* Version Independent ID: 853fe2a9-d654-98a3-7635-c30a450cdbdc
* Content: [Get product data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/get-product-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-product-data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by EliotSeattle** [comment]
Hi @moolwalk.
Thanks for the feedback. This particular feedback channel is for *documentation* feedback rather than *product* feedback. In the future, for ideas or suggestions (or complaints) about the actual product, click **Send feedback about: This product** at the bottom of the page, rather than **Send feedback about: This page**, and you'll be redirected to the [Windows developer feedback site](https://wpdev.uservoice.com/).

I happen to be close personal friends (cough cough) with the Dev lead for this area, though, and I will forward this suggestion to him, so you need not use the tool this time.

Cheers,
Eliot
