### ISSUE TITLE
What/where is the "checked build distribution medium"?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-driver-docs#1523]
> Use the **checked build distribution medium** to install the checked build.

Where/how do you get the "checked build distribution medium"?
Perhaps it's included in the WDK, but there's nothing that indicate that at all, instead, referring to a "checked build distribution medium" indicates almost like it's a physical medium you should get from somewhere.

Also, if it is in the WDK, then there really need to be some more info on how to actually install the checked build.
Do you create a DVD/USB with the checked build which you boot from to install it? Or do I install it from within windows and it overwrites the current installation?  What about  using it with dual boot and installing it on a partition of it's own?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca542ef-731c-4d07-c801-ee80a0cd3ddc
* Version Independent ID: d8744094-ca53-05eb-1103-9f6ffe557f2b
* Content: [Installing the Complete Checked Build - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/installing-the-complete-checked-build#feedback)
* Content Source: [windows-driver-docs-pr/devtest/installing-the-complete-checked-build.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/installing-the-complete-checked-build.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by DOMARS** [comment]
@Bartolomeus-649 - As it turns out, checked builds of Windows are no longer distributed. Checked builds are only available on older versions of Windows, before Windows 10 version 1803. So I added a note about this. Instead of checked builds, use tools such as Driver Verifier and GFlags to check driver code in later versions of Windows. Thanks for filing this issue and sharing what you were seeing, and the interest in improving our docs.
