### ISSUE TITLE
WINDOWS_v100_SERVER_X64_RS5_FULL for signing request will casuing problem of submission

### ISSUE THREAD

**Issue by puffelyang** [MicrosoftDocs/windows-driver-docs#1555]
It seems like the "WINDOWS_v100_SERVER_X64_RS5_FULL" is either not supported for "requestedSignatures" field yet, or at least not for attestation signing. When it was included, the commit will be received, but always fail, and even cause the driver information page on the portal been messed up (check 1152921504607696719 for example). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c20769b-d969-a51a-4eb3-f9cc27875f28
* Version Independent ID: 853fe2a9-d654-98a3-7635-c30a450cdbdc
* Content: [Get product data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#product-resource)
* Content Source: [windows-driver-docs-pr/dashboard/get-product-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-product-data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by EliotSeattle** [comment]
Hi @puffelyang 
I apologize for not responding to this, and I hope and trust that you've since found a solution as to why this wasn't working for you. 

This feedback forum gets sent to the Windows driver documentation team. We use it to track ***documentation*** issues. The Hardware Dev Center Support folks are the right people to help investigate a customer problem with submissions, like this. To open a ticket with the support team:

1. **First**, sign into your hardware dev center account, and *then*...
2. Go to [Hardware Dashboard FAQ](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq), where you'll find this passage: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

It's important that you sign into your account first.

If support, working with the dashboard developers, finds that something needs to change in the strings, we'll then update that here. I hope this helps, and again, I apologize for not picking this up in a timely fashion.
Eliot
