### ISSUE TITLE
Supporting Direct3D Version 12

### ISSUE THREAD

**Issue by Ocasio-J** [MicrosoftDocs/windows-driver-docs#1570]
Documentation for Direct3D 12 is missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8543272-7482-e484-3294-292cbf6aab90
* Version Independent ID: 43074bab-879d-218b-7e8d-991dc6905f87
* Content: [User-Mode Display Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/user-mode-display-drivers)
* Content Source: [windows-driver-docs-pr/display/user-mode-display-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/user-mode-display-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @Ocasio-J , thanks for reporting this. [D3D V12 refpages](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d12umddi/index) exist, but you are correct that conceptual material is missing. I've filed an internal work item to generate D3D V12 conceptual docs at a future time. I am going to close this issue since reference material is available.
