### ISSUE TITLE
Confusing SignedMinimum value for KSPROPERTY_AUDIO_PEAKMETER

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs#1629]
Hello,

This description states that the minimum value must be -32768, while the description of KSPROPERTY_AUDIO_PEAKMETER2:

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-audio-peakmeter2

mentions the 0x8000 instead.

0x8000 is -32768 in 16-bit representation, but the type of SignedMinimum is LONG (32-bit), so a simple assignment like

Range.SignedMinimum = -32768;

will result 0xFFFF8000, not 0x8000.

Please add a clarification, should a driver return either 0xFFFF8000 or 0x8000 in SignedMinimum for KSPROPERTY_AUDIO_PEAKMETER.

With best regards,
Eugene

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18ae6d4-a378-f3c2-3623-8240b80eb13e
* Version Independent ID: fd9d315a-491e-97cc-aa9b-de4b35e6ae40
* Content: [KSNODETYPE\_PEAKMETER - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksnodetype-peakmeter#feedback)
* Content Source: [windows-driver-docs-pr/audio/ksnodetype-peakmeter.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/ksnodetype-peakmeter.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@emuzychenko - I worked with the dev team to clarify the range and sign of peakmeter2. As it turns out KSPROPERTY_AUDIO_PEAKMETER and KSPROPERTY_AUDIO_PEAKMETER2 represent the values in a different way. That is now summarized in the table in this topic. We also worked to highlight that everyone should be using KSPROPERTY_AUDIO_PEAKMETER2 that was introduced in Windows 8.

Thanks for providing a short, specific description of the issue with the topics and your interest in improving the audio driver docs.
