### ISSUE TITLE
 Not working TTD in WinDbg

### ISSUE THREAD

**Issue by nim** [MicrosoftDocs/windows-driver-docs#1712]
I'm trying [TTD](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview), but after attach(with admin rights) i have this error:

![1](https://i.imgur.com/yYP546G.png)
![2](https://i.imgur.com/Y9J2Wa5.png)

I have instaled VS2019, Win SDK and WDK. Why it not working?

**Comment by DOMARS** [comment]
@nim - There are a number of reasons that you may not be able to record a process, for example with a protected processes. See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview#things-to-look-out-for
To isolate the issue, try recording notepad, to validate that that issue is indeed with the target process. 

Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[OSR's windbg List](https://community.osr.com/categories/windbg)
