### ISSUE TITLE
Unable to extract and upload PackageInfo.xml

### ISSUE THREAD

**Issue by toonetown** [MicrosoftDocs/windows-driver-docs#1885]
When attempting to perform Attestation signing, I am now getting an error about missing PackageInfo.xml when uploading the file to the partner center.  However, this document does not explain that file, or its contents - nor does it list it as a requirement for attestation signing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed287852-04b7-1569-fd51-2640cfa24f57
* Version Independent ID: a8ce732f-5b41-f1ce-e37d-a7c2794546a4
* Content: [Attestation signing a kernel driver for public release - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Thanks for the feedback, @toonetown, and apologies for the delay.

I see in https://social.msdn.microsoft.com/Forums/ie/en-US/2e4e98bd-49ce-4d44-bee1-68cc79d23c14/unable-to-extract-and-upload-packageinfoxml?forum=whck that this was due to a temporary server error and has since been resolved.

Sorry you had trouble, and glad it's fixed!
