### ISSUE TITLE
Reference to a non-existing item

### ISSUE THREAD

**Issue by ern0** [MicrosoftDocs/windows-driver-docs#1909]
"When you install Visual Studio 2019, select the »Desktop development with C++ workload«." There is no such. The closest one is "Windows Desktop Application".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#feedback)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by ern0** [comment]
Version:
 Microsoft Visual Studio Community 2019
 Version 16.3.9
 VisualStudio.16.Release/16.3.9+29509.3

**Comment by EliotSeattle** [comment]
Bill, can you look at this quickly?

**Comment by billlattimer** [comment]
@EliotSeattle Reviewing now.

**Comment by billlattimer** [comment]
AB#146084

**Comment by billlattimer** [comment]
@ern0, the option will appear in the Visual Studio Installer rather than in Visual Studio. You can open the installer directly from your menu, or when you go to "Create a new project" you'll see a prompt for "Install more tools and features" which will open Visual Studio Installer for you. 

![image](https://user-images.githubusercontent.com/49699908/75583485-8a115100-5a22-11ea-9590-deefad7d3dcc.png)
