### ISSUE TITLE
Unsigned binaries.

### ISSUE THREAD

**Issue by pareshverma91** [MicrosoftDocs/windows-driver-docs#1920]
Running sigcheck from Sysinternals suite on the poolmon binary installed from the link "Download WDK for Windows 10, version 1903" (https://go.microsoft.com/fwlink/?linkid=2085767) shows the following:

> PS C:\Users\PAVERMA> C:\Users\PAVERMA\Downloads\SysinternalsSuite\sigcheck.exe C:\delete\poolmon.exe
>
> Sigcheck v2.73 - File version and signature viewer
> Copyright (C) 2004-2019 Mark Russinovich
> Sysinternals - www.sysinternals.com
> 
> c:\delete\poolmon.exe:
>         Verified:       Unsigned
>        Link date:      3:29 PM 7/20/1954
>        Publisher:      n/a
>        Company:        Microsoft Corporation
>        Description:    WDK Tool
>        Product:        Microsoft« Windows« Operating System
>        Prod version:   10.0.18362.1
>        File version:   10.0.18362.1 (WinBuild.160101.0800)
>        MachineType:    64-bit
As such running it on production systems is bound to raise alerts. Could the published links be updated to only include Microsoft signed binaries?

**Comment by DOMARS** [comment]
@pareshverma91 - As this request relates to providing product input on the sysinternals suite and not the docs, I would consider using the sysinternals community forums documented here: https://docs.microsoft.com/sysinternals/community. This git issue system is focused on providing input on specific doc topics, so will close this issue here.
