### ISSUE TITLE
More information needed about dirid = 13

### ISSUE THREAD

**Issue by sarman1998** [MicrosoftDocs/windows-driver-docs#1962]
In the  INF DestinationDirs section, section.  "This setting won't work for some devices"  
This really leaves the reader hanging!
 - How to determine in dirid 13 should be used
And/Or at least
 - How things will fail if dirid 13 is used and it should not have been.
If I knew the answers to either of these, I would provide some suggested text but alas, I don't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5fa76b-6c2e-8f5e-7e96-ceb1c726842b
* Version Independent ID: 48a29c52-9907-9b1a-1dc2-3365c2d021d0
* Content: [Getting started with Universal Windows drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers#feedback)
* Content Source: [windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hey @sarman1998 apologies for the delay.  The docs have changed a bit in this area since you opened this issue, here's what's up in the latest.

Basically, you want to use dirid 13 to write a [DCH compliant](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/dch-principles-best-practices) driver.   The [DCH Example](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/dch-example) shows you how you can accomplish this. (You can Ctrl+F for 13 on these pages.) 

Info on other dirids is here -- https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-dirids

And finally, driver package isolation talks about this a bit -- https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/driver-isolation

Let me know if you still have issues here and I can loop in relevant folks as needed.
