### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by goconnor23** [MicrosoftDocs/windows-driver-docs#1989]
Error	C1083	Cannot open include file: 'ntifs.h': No such file or directory (compiling source file access.c)	sys	C:\Users\labstab\source\repos\dokany\sys\dokan.h	32	

The ntifs.h file exists in C:\Program Files(x86)\Windows Kits\10\Include\10.0.18362.0\km
Do I need to do something to make  Visaul Studio pick up the SDK/WDK files? Or am i missing something else?

**Comment by EliotSeattle** [comment]
Hi @goconnor23 
Thanks for submitting this GitHub Issue. 
As far as I know, no action needs to be taken to access the header file. This sounds like a regular file access problem, rather than a WDK issue. Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the MSDN Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question there, and like-minded developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.
Eliot
