### ISSUE TITLE
Can "FundamentalDeviceResetTriggeredOnD3ToD0" also apply to non-Desktop systems?

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs#2091]
I'm fielding a question from our BIOS teams.
Technically, can't FundamentalDeviceResetTriggeredOnD3ToD0 also apply to mobile systems?   If so, can the verbiage "desktop" be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3c20c6-017c-464c-2cb4-fedc32d796d5
* Version Independent ID: a9c13e82-40e8-8025-2a63-dfe91be18df3
* Content: [Device Specific Data (_DSD) for PCIe Root Ports - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/pci/dsd-for-pcie-root-ports#directed-deepest-runtime-idle-platform-state-drips-support-on-pcie-root-ports)
* Content Source: [windows-driver-docs-pr/pci/dsd-for-pcie-root-ports.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/pci/dsd-for-pcie-root-ports.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @tzimmer1 
It took me a little while to sort out the subtleties, but I've amended that entry to be clearer. I've merged the changes, and they should appear on the live site this evening. The passage now reads:

"This ACPI object must be implemented in the ACPI scope of every PCIe Root Port/slot that is accessible to the user on Modern Standby-enabled systems that are capable of implementing the [Directed Power Management Framework (DFx)](../kernel/introduction-to-the-directed-power-management-framework.md)."

The problem comes when someone modifies a system, a difficult thing to do for laptop and mobile systems. What the manufacturer ships is usually the hardware that the user is running. On a desktop system, though, a user can more easily put in a device that is not DFX capable, and Windows would need to fall back to using PS4 on the root port. So while it is supported in both mobile and desktop systems, the scenario really only exists on desktop systems.

Hope this helps,
Eliot
