### ISSUE TITLE
Trigger TDR

### ISSUE THREAD

**Issue by ashwalk85** [MicrosoftDocs/windows-driver-docs#2101]
Is there a way to trigger the function manually - and doing so, diagnose a possible hardware failure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1659b1-d9fa-8bbe-14a9-76f6dff30ecb
* Version Independent ID: a4b8c247-17c3-5ccd-e5eb-4878200680b5
* Content: [Thread Synchronization and TDR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/thread-synchronization-and-tdr#feedback)
* Content Source: [windows-driver-docs-pr/display/thread-synchronization-and-tdr.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/thread-synchronization-and-tdr.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@ashwalk85 , thanks for the great issue, and I'm so sorry for my slow response! It turns out that there is indeed a WHLK test you can use to simulate a TDR. I added mention of the WHLK TDR-related tests on the newly overhauled [Testing and debugging TDR page](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys) page.
