### ISSUE TITLE
Update "initial" driver package

### ISSUE THREAD

**Issue by sychevathotmail** [MicrosoftDocs/windows-driver-docs#2151]
after the driver is published to windows update, I can't find a way to update it with newer package.  
![image](https://user-images.githubusercontent.com/63258674/78593632-900e0500-780c-11ea-98df-b1233e79cc3f.png) implies that there should be a way, but clicking "here" just takes me to existing driver form

**Comment by EliotSeattle** [comment]
Thanks, @sychevathotmail 
Can you please tell me the page title or URL for the topic this occurs on?
Thanks,
@EliotSeattle

**Comment by sychevathotmail** [comment]
Eliot, I log in with my company's credentials at https://partner.microsoft.com/en-us/dashboard/hardware/Search, then pick the previously uploaded (and now signed and published) driver package. Supposedly this page has some ways of uploading new CAB file, such that when I create new "label", I can pick new version.

**Comment by sychevathotmail** [comment]
I followed guide https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-hardware-submission to create "initial" package

**Comment by EliotSeattle** [comment]
Hi @sychevathotmail 
My team creates the topics that *describe* the dashboard. The Hardware Dev Center Support team are the right people to help investigate an issue like this. To reach out to them:
1. **First**, sign into your hardware dev center account, and then 
2. Open a Hardware Dev Center support case for investigation. 
3. Go to 
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
and look for: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

**Please** do let me know if the documentation topics need to be updated because of your issue. 

Best of luck with this.
Eliot
