### ISSUE TITLE
Need more information please

### ISSUE THREAD

**Issue by github-ap-keys** [MicrosoftDocs/windows-driver-docs#2171]
This information is not enough to develop software to use GenericUsbFn.sys. For example, what is the structure of content returned by  IOCTL_GENERICUSBFN_GET_CLASS_INFO? Need code sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab78a743-0b21-6fcb-259c-f7124a5103a1
* Version Independent ID: 4c6e4bd7-e781-dc1a-c9d1-57ca5fcb8b51
* Content: [Communicating with GenericUSBFn.sys from a user-mode service - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/user-mode-services-ufx)
* Content Source: [windows-driver-docs-pr/usbcon/user-mode-services-ufx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/user-mode-services-ufx.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @github-ap-keys  thanks for the feedback and apologies it's taken us so long.  Your question is now tracked in a Microsoft-internal bug.  I do not have an ETA for when it will be resolved.  Because we have the bug tracking it now, I am going to close out this issue.

If you would like me to notify you if and when I get an answer, please just reply to me here and I will see it and make a note.

Thanks for caring about the docs!
