### ISSUE TITLE
The link to WDK insider preview download of Japanese version page is incorrect

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/windows-driver-docs#2238]
@ahidaka commented 18 hours ago

At the link of the Japanese page
https://docs.microsoft.com/ja-jp/windows-hardware/drivers/download-the-wdk

Section of "Related downloads",
link of "Download the WDK Insider Preview" indicates
https://www.microsoft.com/ja-jp/software-download/windowsinsiderpreviewWDK
but its is missing.

This link should be followings.
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewWDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @v-radelg 
The ja-jp page works for me. When I look at the source for the page, I see this for the Related Downloads:

\## \<a name="related-downloads">\</a>関連するダウンロード

\* \[WDK Insider Preview のダウンロード]\(https://www.microsoft.com/software-download/windowsinsiderpreviewWDK)

This is by design. Note that there is no locale identifier. When a customer clicks that link, they are taken to the microsoft.com domain to find the resource, windowsinsiderpreviewWDK. If their browser is set to the ja-jp locale AND our site has a ja-jp version of the page, it serves up the localized version. If there is no localized version, the site serves up the default version, in our case en-us.

However, if we hardcode a locale in the link the server either only serves up that locale for the request, or can show a 404 if there is no version for that locale.

So, when I click the neutral version of https://www.microsoft.com/software-download/windowsinsiderpreviewWDK, my browser renders

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewWDK

but for someone whose browser locale is set differently (**xx-XX**), they'll get 
1) the page in their locale, if we have it
2) or the page in en-us

If you are not experiencing this behavior, it sounds like a bug with microsoft.com. Feel free to follow up with me in email.

Eliot
