### ISSUE TITLE
What about case #2?!

### ISSUE THREAD

**Issue by jcmcmicking** [MicrosoftDocs/windows-driver-docs#2251]
You laid out 2 cases and only answered 1 of them. Case 2 has been a problem with my Surface bluetooth keyboard forever. Once, I found the magic Power Managmement tab in Device Manager and that solved it for a bit, but now a Windows Update has changed the game and it still goes to sleep even when none of the power management tab checkboxes are checked for any bluetooth or UPS devices, hubs, ports, et al.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ffbb25-1a64-53a4-ffd6-daf4f26abf08
* Version Independent ID: 47f17e27-42e8-7b7d-d56a-18fd8e78f88b
* Content: [Power management for HID over USB - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/power-management#feedback)
* Content Source: [windows-driver-docs-pr/hid/power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/power-management.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@jcmcmicking, thanks for opening this issue. The document referenced is for developers to create device drivers rather than end-users facing issues as you describe. 

I do understand the frustration; this issue has been noted in the Microsoft Communities and there is guidance there that may prove helpful. Note that often these issues can be traced to BIOS setup causing the radios (USB, BT, etc.) to sleep on a timeout. 

Please see: 

https://support.microsoft.com/en-us/windows/troubleshoot-problems-with-your-microsoft-mouse-or-keyboard-5afe478d-6402-d72b-93b9-e4235fd5c4cd?ui=en-us&rs=en-gb&ad=gb

https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/keyboard-and-mouse-stops-working-after-a-specific/4dc3d072-15b3-47cd-8f64-ca8bf3ff1b97
