### ISSUE TITLE
Suddenly kernel debugging causes host-os bugchecks

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-driver-docs#2273]
This is a new problem I just started to have for some reason, everything was working perfectly fine before.

Usually I kernel debug using VS over NET or Serial. Just recently, whenever I try to break into the remote machine I am debugging in VS, VS will exit without any warning, no cleanup. It simply terminates. Even more strange, on my host OS that I am remotely debugging from, the reliability monitor shows three `Hardware Error` bugchecks all with codes `LiveKernelEvent` `41a1`. I can't find this bugcheck code on the bugcheck reference sheet. Also, the reliability monitor shows VS crashing with code `STATUS_HEAP_CORRUPTION.`

This does not occur when using `WinDbg` alone. Also, the setting to view disassembly when source is not available is toggled to ON in VS. It seems like VS crashes when the disassembly is being read. But I don't know why it is causing `KernelEvents` on my host OS.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97eed641-8cd3-4359-aee7-2f14acd28b24
* Version Independent ID: c0c6d81e-4487-cd62-9dcd-9ce3b14f98e0
* Content: [Setting Up Local Kernel Debugging of a Single Computer Manually - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-local-kernel-debugging-of-a-single-computer-manually)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-local-kernel-debugging-of-a-single-computer-manually.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-local-kernel-debugging-of-a-single-computer-manually.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@AzAgarampur -  Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
This feedback mechanism is for requests about the documentation.  

As it turns out, Visual Studio Kernel debugging, is no longer supported after version 1507 as described in the VS debugging topics - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/performing-kernel-mode-debugging-using-visual-studio

Good luck with your kernel debugging work.
