### ISSUE TITLE
Is the kernel really freezing my code this long?

### ISSUE THREAD

**Issue by HenkSchutte** [MicrosoftDocs/windows-driver-docs#2296]
I am testing a tiny Windows Real-Time class thread that runs a Sleep(10) and then performs some code that finish in appr. 100 ns and this for"ever". On an oscilliscope I can observe the Ethernetframe that was started every 10 millisecs. But every 0.5 to 10 seconds there is a significant long (around 200ms) freezing observed of the CRC signals. I accept that Windows is not a real-time o.s, but freezing user code during 200ms is quite rude, I think.
Is there anybody that knows what kernel thing happens during these 200ms intervals, or how this can be controlled? Reducing the 200ms to 50ms would already help a lot.

Thanks for any suggestion,
Henk Schutte
Amsterdam NL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae60e131-28fe-cbda-f41f-62771cbb8db1
* Version Independent ID: bb54c373-19d8-77fd-bc63-d02b69fe0075
* Content: [Always Preemptible and Always Interruptible - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/always-preemptible-and-always-interruptible)
* Content Source: [windows-driver-docs-pr/kernel/always-preemptible-and-always-interruptible.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/always-preemptible-and-always-interruptible.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Henk, thanks for the question.  I'd recommend starting with https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer to see if you can figure out a root cause. 

 I'm not an expert in performance, but you might try the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

Again, thanks for reaching out. Best of luck with this issue.
