### ISSUE TITLE
what is the differences between compatible ID and hardware ID

### ISSUE THREAD

**Issue by zhengxi0922** [MicrosoftDocs/windows-driver-docs#2337]
[Enter feedback here]

what is the differences between compatible ID and hardware ID?
since both IDs have the same format, why do we need compatible IDs?
and what about the priority?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ed123-4144-3845-af3d-e5013ce8cc41
* Version Independent ID: 50b0c5f8-7190-786a-3cde-f7501d051d67
* Content: [Compatible ID - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/compatible-ids)
* Content Source: [windows-driver-docs-pr/install/compatible-ids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/compatible-ids.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
If Windows cannot locate an INF file that matches one of a device's hardware IDs, it uses compatible IDs to locate an INF file.

A compatible ID is usually less specific, in order to customize a setting across a broader set of devices.

Also see https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-custom-hardware-ids-and-compatible-ids

**Comment by zhengxi0922** [comment]
OK
But still, why inf creator don't use the hardware id at the first time?
"A compatible ID is a vendor-defined...."so who is the vendor?
e.g. we have a touchpad device, so the compatible ids are created by the touchpad supplier?

**Comment by zlockard** [comment]
The vendor would be whoever is making the touchpad.  The general way to think about hardware or compatible IDs is that they're a contract between the device and the driver.  If a driver installs on a hardware ID, it is fulfilling a contract to provide full functionality to a device.  A compatible ID is a contract that says that at least basic functionality is implemented.  A reason to do this might be so that a generic driver that matches compatible IDs might work on a large number of devices, for example a lot of the driver built into Windows match compatible IDs.

**Comment by tedhudek** [comment]
Thanks @zlockard I added this info to the bottom of https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-custom-hardware-ids-and-compatible-ids

**Comment by zhengxi0922** [comment]
well understood.
thank you guys.
@zlockard @tedhudek
