### ISSUE TITLE
Sample code needs to be updated to compile clean for customers usage

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/windows-driver-docs#2341]
[Enter feedback here]
Sample code in the link is psuedo code but needs to be updated to code that compiles.   Request is to update the example to be code that compiles for customer usage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdefa0-ac98-177b-d923-17d0b9014d06
* Version Independent ID: ab21e88a-1a87-0449-24df-a54a07b18eae
* Content: [CCD Example Code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/ccd-example-code)
* Content Source: [windows-driver-docs-pr/display/ccd-example-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/ccd-example-code.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@snakex2000 , thanks for pointing out that some of the pseudocode wasn't commented. For the sake of time, I've updated the "code block" so that it is all pseudocode now. If we find some spare cycles in the future, we'll convert the pseudocode to sample code. I'm guessing that you'll find the pseudocode quick and straightforward to follow. Thanks again!
