### ISSUE TITLE
Bug check 4E  Param 4 of 0x0000000000000001 not documented

### ISSUE THREAD

**Issue by harrystein** [MicrosoftDocs/windows-driver-docs#2365]
I received (Windows 10, version 2004) bugcheck:

Insertion strings: 0x0000004e (0x0000000000000099, 0x0000000000004987, 0x0000000000000002, 0x0000000000000001)

Been getting a lot of these for a year and can't use debugger to see which driver causes this.  Other tools just say "indeterminate driver" point to a driver but would be nice if more tools can assist in dump to point to driver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a848f5bb-5440-1e61-f7bd-7f081ec6b243
* Version Independent ID: 6c05667b-00e6-0f40-d6b4-f28ae5274e4b
* Content: [Bug Check 0x4E PFN_LIST_CORRUPT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x4e--pfn-list-corrupt)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x4e--pfn-list-corrupt.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x4e--pfn-list-corrupt.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@harrystein - Some memory errors can be difficult to track down. In general with out the debugger and an understanding of Windows memory usage it can be very difficult. Sometimes the event log may log a related event right before the blue screen occurs, so that would be one place to look. On the parameters, the leading zeros, are not typically shown, so it would be 0x1. It looks like that and 0x99 are documented currently, so I don' think there is a docs bug here. You may want to look at the directions in https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data that describe running memory diagnostics to rule that out. Good luck with tracking down your issue.
