### ISSUE TITLE
Surface laptops don't have scroll lock key to initiate a crash

### ISSUE THREAD

**Issue by acellarius-msft** [MicrosoftDocs/windows-driver-docs#2545]
The page talks about using the scroll lock key, but Surface laptops typically don't have that key.
An alternative should be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b225392c-a057-a2b6-28be-a0939f4834ba
* Version Independent ID: d94f25da-8679-f2b0-ed24-4b40712bf695
* Content: [Forcing a System Crash from the Keyboard - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard)
* Content Source: [windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Hi @acellarius-msft - Thanks for the suggestion. A few ideas. We just added a power button crash topic, so that is one option - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-with-the-power-button This topic describes how you can re-map the scroll key in "Defining Alternate Keyboard Shortcuts to Force a System Crash from the Keyboard", so that is another option. There are of course many Windows Surface devices, so I would leave it to the surface docs crew to decide if they want to cover that in their docs. They do describe the power button behavior across the surface product line in this article. https://support.microsoft.com/en-us/help/4036280/surface-force-a-shut-down-and-restart-your-surface
