### ISSUE TITLE
MmMapIoSpace + HV + kernel debugger BSOD bug

### ISSUE THREAD

**Issue by vivianezw** [MicrosoftDocs/windows-driver-docs#2660]
There seems to be an issue with MmMapIoSpace. It might be a bit more complicated than it looks on the first view. Please bear with me. Observation: MmMapIoSpace causes a BSOD when accessing memory which "seems good" from point of the OS/memory manager, but is forbidden by the Hyper-V layer below the OS for any reason, but **only** when attached with kernel debugger, otherwise it can be catched by a try-except statement (because it is still forbidden memory, and therefore must be handled as an exception). The try-except statement will not work in presence of an attached kernel debugger and forcibly crash into a MEMORY_MANAGEMENT (1a) BSOD. 

What I'm saying is that _specifically on a Hyper-V machine_, _and only with the kernel debugger attached,_ possibly also working with _verifier_ instead of kernel debugger, there will be an _unvoidable_ BSOD.  I'm not arguing that the Hyper-V may make any portion of the memory inaccessible. That's totally fine. 

Summary:
* with KD attached: BSOD of debuggee.
* without KD attached: no BSOD, a try-except statement is able to handle the 'bad' access to Hyper-V forbidden memory.
* Without Hyper-V layer (host), this does not happen. (no read error happens that would cause an exception.)
 
From my archived logs (it's from https://github.com/Velocidex/WinPmem):

FAULTING_SOURCE_CODE:  
    91:   // Map exactly one page.
    92:   try
    93:   {
    94:       mapped_buffer = Pmem_KernelExports.MmMapIoSpace(ViewBase, PAGE_SIZE, MmCached); 
    95:   }  <==
    96:   except(EXCEPTION_EXECUTE_HANDLER)
    97:   {
    98:       DbgPrint("ERROR: MmMapIoSpace failed to map 0x%lx with page size 0x%x\n", ViewBase.QuadPart, PAGE_SIZE);
    99:   }
   100: 

MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 0000000000001233, The subtype of the bugcheck.
Arg2: 0000000000000103

This could be dangerous, because a driver might get an address by *someone* and cannot do any sanity test. There is simply no way to avoid the crash. Some evil entity could use this to feed such "forbidden" addresses to an unsuspecting driver, which then has no chance of avoiding the BSOD. Of course this only happens with a kernel debugger attached... and Hyper-V layer. Rumors says that this works also with _verifier_ instead of kernel debugger, and in this case, it might become a more dangerous scenario. (I never tested with verifier in this scenario and cannot say if this is true.)

**Comment by tedhudek** [comment]
Hi @vivianezw,

First thank you for the report - we really appreciate that you took the time to provide the details.

I circled back with the team, and it turns out this is expected behavior from the OS, and not a bug.

Bugcheck 1A/1233 means the caller is trying to map a page which is not locked down.  Meaning the page can be reallocated at any time for any use, thus making the mapping not only point at memory that can be constantly changing contents – but can also be changing cache attributes which means the caller’s mapping would violate hardware coherency rules.

MmMapIoSpace should only be used with pages that are locked down (ie, belong to an MDL’s locked pages or I/O space), otherwise the owner of the memory could free it (or the memory could be paged in/out etc).

In the example below, page 103 was *NOT* locked down, which is a violation of the above.  With the verifier on, we bugcheck these since we have the violating driver in hand.

I've added a note to the doc page for MmMapIoSpace tp this effect.

Thanks again for reaching out!
