### ISSUE TITLE
push/pop instruction of Meaningless function seems incorrect

### ISSUE THREAD

**Issue by bupjae** [MicrosoftDocs/windows-driver-docs#2711]
According to the document, assembly of Meaningless function begins as follows:

```
Meaningless:
010010e0 push    rbx                    ; save
010010e1 push    rsi                    ; save
010010e2 push    rdi                    ; save
010010e3 push    r12d                   ; save
010010e5 push    r13d                   ; save
010010e7 push    r14d                   ; save
010010e9 push    r15d                   ; save
010010eb sub     rsp,0x2c0              ; reserve stack
010010f2 mov     rbx,r9                 ; rbx = pszExe
010010f5 mov     r12d,r8d               ; r12 = fUnique (zero-extend)
010010f8 mov     r13d,edx               ; r13 = dispid  (zero-extend)
010010fb mov     rsi,rcx                ; rsi = pdisp
```

As far as I know, in x64, we cannot push 32-bit general purpose register (r12d ~ r15d); instead we should push 64-bit general purpose register (r12 ~ r15).

Same applies to pop instructions at the assembly of end part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b660a04-857a-f142-253c-6d5742fd3070
* Version Independent ID: 9922156a-5d62-26b1-327e-7c83f00d28b0
* Content: [Annotated x64 Disassembly - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/annotated-x64-disassembly)
* Content Source: [windows-driver-docs-pr/debugger/annotated-x64-disassembly.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/annotated-x64-disassembly.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@bupjae - Thanks for passing on your thoughts on the use of registers in the illustrative code snips shown. It is possible that how the  r12d ~ r15d registers are displayed has changed since this sample compile was done. And it is possible that different compiler options may impact register use as well. It is also possible that the decompile that was used, is showing the upper or lower part of the registers. For more detail on all of this,  see [x64 Architecture](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/x64-architecture). Also you can enable asm source code debugging to enable a closer to code experience. This is discussed in https://docs.microsoft.com/windows-hardware/drivers/debugger/debugging-in-assembly-mode In general this walkthrough is very basic and for more detailed information on register usage and overlap, refer to other more complete topics, such as the x64 tutorial from Intel. https://software.intel.com/content/www/us/en/develop/articles/introduction-to-x64-assembly.html. I added a few links to the topic to provide more information on the 32 64 bit views of disassembly. Thanks again for your interest in the docs and providing this input on the x64 disassembly topic.
