### ISSUE TITLE
kdnet not running at all on Windows 7, "failed to set dbgsettings" on Windows 10

### ISSUE THREAD

**Issue by adigostin** [MicrosoftDocs/windows-driver-docs#2712]
On Windows 7, it complains about missing api-ms-win-xxxxx.dll files. I manually downloaded and copied a few of them next to the executable, but it kept complaining about other similar files missing so I gave up.

On Windows 10, all I get as error is:
_Enabling network debugging on Realtek PCIe GBE Family Controller.
Failed to set dbgsettings._
That error message is not at all helpful.

I get the impression that a lot more steps are needed in this documentation page.

LATER EDIT:
I had tried the above using the debugging tools from the latest SDK (10.0.19041.0 at the time of writing this).
Afterwards I tried kdnet.exe that comes with Windows SDK 10.0.15063.468 and this one _does_ work in Windows 7. So I think you should at least update the documentation on this page and related ones that claim Windows 7 compatibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51b628-bb73-f32f-5a81-fefce12a4b49
* Version Independent ID: e07e2607-fd13-5517-510c-77bf717125c8
* Content: [Setting Up KDNET Network Kernel Debugging Automatically - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@adigostin - Glad that you were able to get the kernel debugger client working. More detail on troubleshooting and additional steps are provided in the manual configuration topic - [Setting Up KDNET Network Kernel Debugging Manually](https://docs.microsoft.com/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection). But as the KDNET utility generates a unique key, it is more secure and reliable, so that method is recommended. As I think we stopped supporting Windows 7 in January of this year, I will check on that, and work to update references to versions of Windows. Thanks for this input and good luck with your debugging work.
