### ISSUE TITLE
Why are debugging tools classified under "windows drivers"?

### ISSUE THREAD

**Issue by billw2012** [MicrosoftDocs/windows-driver-docs#2728]
The debugger interfaces are widely used by anyone wanting to handle crash reporting for their software. I would never think to look under hardware/driver development to find this stuff, they are just general development tools aren't they? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68be4f3a-a792-45da-3c43-533aed0f89b1
* Version Independent ID: 2cc4d72a-3053-6f06-8613-61e7a144e094
* Content: [Debugging Tools for Windows (WinDbg, KD, CDB, NTSD) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/)
* Content Source: [windows-driver-docs-pr/debugger/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@billw2012 - That is an interesting question. Historically the work for kernel code (vs. user mode app dev work) was done by device driver developers. Many device developers write code to to talk to hardware, so that is I think why the debugger docs have been associated with the "Windows Driver Kit" or WDK. Other dev environments with their debuggers such as Visual Studio, VS Code or Eclipse are typically used by managed code developers.  The good news is using a search engine, the WinDbg debugger docs can be located. But thanks for the feedback on where the debugging tools might be located on docs.microsoft.com.
