### ISSUE TITLE
IIS setup for symbol proxy server is not clear

### ISSUE THREAD

**Issue by billw2012** [MicrosoftDocs/windows-driver-docs#2729]
It doesn't map to IIS 10 at all, I had to to very different steps (create symbol virtual directory, convert to application).
It also doesn't mention that you need to add MIME types for .pdb, .pd_ and .ptr for them to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c9d31e-4e65-67b9-5460-c8414301fab4
* Version Independent ID: 20a6a902-0426-d83d-227b-56ad92ab1299
* Content: [Configuring IIS for SymProxy - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-iis-for-symproxy)
* Content Source: [windows-driver-docs-pr/debugger/configuring-iis-for-symproxy.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/configuring-iis-for-symproxy.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@billw2012 - Thanks for filing this issue and your interest in the symproxy docs. I worked to update the topic to better reflect the current day IIS. I also added a link to the IIS docs, so that can be consulted for information about the various versions. I also added links to the related topics, as this topic, fits in a larger process that is described in the adjacent topics. Symproxy is typically configured in conjunction with symsrv, so the best approach is to review the related topics - that I now have links to, in this topic. These improvements should be helpful to future readers, so thanks for filing this issue, and thanks again for your interest in the symbol server docs.

**Comment by billw2012** [comment]
I noticed this, thanks! I actually ran into a general problem with setting up symproxy that isn't mentioned in the docs at all: it seems it is just not possible for a SymProxy to refer to http servers at all when running under IIS, as the latest versions of dbghelp.dll use WinHttp only and are not capable of accessing http (or perhaps specifically https). I have to revert to a very old version of dbghelp.dll to be able to set the DBGHELP_WININET flag (which isn't supported in new versions), to be able to use the MS symbol servers via SymProxy. 

Perhaps you could talk to whoever writes dbghelp directly and ask them to clarify this behavior as the only discussion of it is from very old list srv topics (2006 or something).
