### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DaveWut** [MicrosoftDocs/windows-driver-docs#2777]
Hello, 

How can I use the commands available through the debugging extension Kdexts.dll? I'm quite new to this world. Do I need WinDbg? If so, do I need to attach myself to the kernel? 

Thank you for your help! 
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652ca8b5-e8a3-2e1f-ddd3-c53abc78a1f7
* Version Independent ID: cf47a589-aa9a-4495-51ec-6f138b3b9c82
* Content: [Windows Hardware Error Architecture Debugger Extensions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/windows-hardware-error-architecture-debugger-extensions)
* Content Source: [windows-driver-docs-pr/whea/windows-hardware-error-architecture-debugger-extensions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/whea/windows-hardware-error-architecture-debugger-extensions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by DOMARS** [comment]
@DaveWut - The Windows kernel debugger is a pretty complex undertaking. I added links to getting started and a download for the newer WinDbg Preview, which as a more modern UI. 

There are also books, and even a channel 9 video series  *The Defrag Tools Show* WinDbg - Episodes 13-29 https://channel9.msdn.com/Shows/Defrag-Tools

This step by step lab takes you through the configuration on a supported network card. https://review.docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-?branch=domars-whea-april

Because it is helpful to dead stop execution at certain points to look at memory values, two machines are normally used. The walkthrough shows how to set a break point, when an item of interest in is active in memory - in scope. This may need to be done to examine the WHEA values, depending on what area you are looking at in kernel mode memory with the debugger. Thanks for the input on this topic, and good luck with your WHEA debugging.
