### ISSUE TITLE
0x124 information is lost unfortunately. 

### ISSUE THREAD

**Issue by moskvach** [MicrosoftDocs/windows-driver-docs#2782]
0x124 information is lost unfortunately.  Please restore it.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x124---whea-uncorrectable-error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc632b2-f4e1-b784-dd1e-878feac077f9
* Version Independent ID: 7a6866f4-3333-f2d1-86d7-dbb3d00925e0
* Content: [Bug Check Code Reference - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference2)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-code-reference2.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-code-reference2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@moskvach - As it turns out, WHEA 0x124 is both a live and a regular blue screen stop code. There are just a handful of stop codes like this. They are now listed on https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference-live-dump#kernel-live-dump-codes
As live dump codes don't blue screen the PC, they are listed in this new section. The dual purpose stop codes, like 0x124, are listed there as well.
