### ISSUE TITLE
What can be the cause of image in memory corruption?

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/windows-driver-docs#2784]
This page describes in detail what the !chkimg extension detects and how it works. It fails to address however what can be concluded from the output. E.g., when the image memory indeed has been corrupted, it is interesting to know the following:

- What are likely causes for the corruption to happen?
  - Corrupted images on disk or bad disk cabling as is suggested here: https://stackoverflow.com/questions/40913080/what-corruption-is-indicated-by-windbg-and-chkimg ?
    - This seems unlikely to me as I think that this would cause very specific events when running DISM (in case of corrupted disk image) or in the event log (disk read failures in case of defective cabling), but it appears to be one of the few generically accepted causes when I search the Internet
  - A buffer overflow or other issue that causes the memory area to be overwritten inadvertently.
    - This seems to be a very likely candidate to me but I'm just learning about using windbg and a confirmation of my suspicion would be greatly appreciated 
  - A file compression/decompression, expansion, transcription, encryption or other technique that is applied for a good reason and is incorrectly reported as memory corruption.
- If this is something bad that should be looked into or something that should normally be expected (maybe dependent on the caus)
- Where to go from here, e.g. to determine if this should be looked into further, and if so, to find the exact cause of the memory corruption and to resolve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5883cc0b-46d0-9c99-ff14-777ae62b1adf
* Version Independent ID: 7039f21c-55f6-0135-ec6b-b89e675d723e
* Content: [chkimg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-chkimg?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/debugger/-chkimg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-chkimg.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@niderost - Thanks for this input and your interest in the debugger docs. I added a new section to this topic to provide a small bit of help on what to do when things don't match using !chkimg. These general tools can at least help to rule out obvious memory hardware errors and storage errors that can be detected. It can also be a driver or the OS that is at fault. As this is a corruption, and at least some part of the OS may have lost integrity, it can indeed be difficult to track down. We just worked to complete additional docs for live dump stop codes. So that would be something to check as well. As we are a small docs team, it is often difficult to carve out time to right additional scenario walkthroughs. But I will add using the debugger to track down OS corruptions to the list. Many times using the event log, and other OS level tools will surface the issue as described in blue screen data (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data) topic. When that works, that is typically at least an order of magnitude easier then looking at the registers and assembly language and trying to back track to what causes the corruption.  Thanks again for your interest in our docs and good luck with tracking down the cause of memory corruption.
