### ISSUE TITLE
SDK download page has version 10.0.19041.0 at the top instead of 10.0.20348.0, making it easy to make a mistake

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/windows-driver-docs#2816]
When I click on the link to install matching Windows SDK for version 10.0.20348.0, the SDK page shows the SDK version 10.0.19041.0 at the top. It is not obvious that there is version 10.0.20348.0 down below. It would be easier if the latest version is at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-drivers-conceptual-docs**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @hwisungi, thanks for the feedback!  We just updated the link in step 1.5 at https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-15-install-windows-sdk-version-2104-build-100203480 so that it now takes you directly to the .iso that you need.  

Thanks again and have a great weekend.
