### ISSUE TITLE
Required instructions for Win32 service un-instalation when installed using component inf

### ISSUE THREAD

**Issue by eshiva0** [MicrosoftDocs/windows-driver-docs#2839]
This page doesn't explain the case for uninstallation of Win32 service where this user service has been installed using component inf.
Explicitly looking for

- Currently once Win32 service is installed using component inf, it runs asynchronously. No more controlled from component INF like software component device disable or uninstall are not impacting the win32 service. Is it expected behavior?
- How to achieve controlling Win32 service from software component device?
- How to delete the service from software component device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5691015-7370-801d-cb4b-bf6d078aded9
* Version Independent ID: 7ecaf651-15c0-a0db-847d-acd509d44a25
* Content: [Win32 Services Interacting with Devices - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/best-practices-win32services-interacting-with-devices)
* Content Source: [windows-driver-docs-pr/install/best-practices-win32services-interacting-with-devices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/best-practices-win32services-interacting-with-devices.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by zlockard** [comment]
The high-level point of the software component INF is so that drivers could delivered via Windows Update.  There is no special logic for them that controls any services.  If you wanted to implement such a thing, you could write a device driver that is installed on the software component that implemented such controls.  Uninstall should work though, if you used AddService to install the service, although this depends on which API was used to uninstall the software component driver.  DiUninstallDriver, for example, should remove the win32 service.
