### ISSUE TITLE
Need to define the GUID used when opening VHDs over the network

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#2864]
Hey Lori,

It appears that `vhdmp.sys` opens the VHD files with an ECP GUID called `{9ecfcb9c-c104-43e6-980e-158da1f6ec83}` prior to calling  [FsRtlMupGetProviderInfoFromFileObject](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlmupgetproviderinfofromfileobject).  This function skips the file system filter stack and so it is important that filters know that they are about to be skipped.

Can we get it added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe6d7e0-23be-145b-ee34-b92df88b3f29
* Version Independent ID: 63d4bdd3-6a36-15bf-2318-3340f295fb7d
* Content: [System-Defined ECPs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/system-defined-ecps)
* Content Source: [windows-driver-docs-pr/ifs/system-defined-ecps.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/system-defined-ecps.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , after much discussion with various devs, I can tell you the following:

- I cannot document this GUID because it is not defined in ntifs.h (or any other public WDK header file)
- This GUID is reserved for system use, but it turns out that its ECP (and therefore it, although it isn't explicitly mentioned) are obtusely documented in the [Remote Shared Virtual Disk Protocol spec](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rsvd/c865c326-47d6-4a91-a62d-0e8f26007d15): the ECP is called SVHDX_OPEN_DEVICE_CONTEXT or SVHDX_OPEN_DEVICE_CONTEXT_V2, depending on protocol version.
- [This blog post](https://techcommunity.microsoft.com/t5/failover-clustering/cluster-shared-volume-csv-inside-out/ba-p/371872) describes different ways that CSVFS dispatches IO. 
 
Sorry I can't doc it - hope this is helpful enough!
