### ISSUE TITLE
The bugcheck 0x139 documentation has no description about Parameter 1 of value 30 (0x1e)

### ISSUE THREAD

**Issue by yujuiwu** [MicrosoftDocs/windows-driver-docs#2891]
[Enter feedback here]
I got bugcheck 0x139 with Parameter 1 of value 30. 

I looked up the document for the meaning of Parameter 1 of value 30, but found that this specific value is absent in the list.

What does Parameter 1 of value 30 mean?
If it is for internal use only, is it safe to just ignore it? Or is there anything I should do about it?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1073c44-369a-9365-a2a7-ea5b064fb1af
* Version Independent ID: 28187f46-abb9-c7cb-9b22-ddd4a2ec9d37
* Content: [Bug Check 0x139 KERNEL_SECURITY_CHECK_FAILURE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x139--kernel-security-check-failure)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x139--kernel-security-check-failure.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x139--kernel-security-check-failure.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Hi @yujuiwu 

Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. Best of luck with this issue.
•	windows-hardware-wdk - https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html
•	OSR's Debugger forum -  https://community.osr.com/categories/windbg

This thread on the OSR forum describes this bug check. 
https://community.osr.com/discussion/292848/kernel-security-check-failure-for-stack-overrun

Transient memory errors can be caused by physical failures and environment factors, and typically require no follow up actions.

If this bug check continues to occur, you could check in the event log and see if there is a specific activity that occurs right before the bug check and look further at the code associated with that event.

As is mentioned in the OSR thread, enabling driver verifier memory pool options, can be a good technique to narrow in on the initial memory write error that leads to other faults and failures downstream.

Thanks for your interest in the Windows bug check docs, and I hope you are able to find an appropriate resolution.
