### ISSUE TITLE
BugCheck 0x139 Subtype 1d

### ISSUE THREAD

**Issue by TheBestYTech** [MicrosoftDocs/windows-driver-docs#2920]
I can not see subtype 1d in the docs. WinDbg Defines subtype 1d as "An RTL_BALANCED_NODE RBTree entry has been corrupted."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1073c44-369a-9365-a2a7-ea5b064fb1af
* Version Independent ID: 28187f46-abb9-c7cb-9b22-ddd4a2ec9d37
* Content: [Bug Check 0x139 KERNEL_SECURITY_CHECK_FAILURE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x139--kernel-security-check-failure)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x139--kernel-security-check-failure.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x139--kernel-security-check-failure.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@TheBestYTech - As it turns out, this topic is providing the decimal value and 0x1D = 29  *An RTL_BALANCED_NODE RBTree entry has been corrupted*. In general in the docs, values that are provided in hex are prefaced by 0x, otherwise base 10 is used.
Thanks for your interest in the debugger bug check documentation, and good luck with your debugging.
