### ISSUE TITLE
how to get the Signature Hash of the UWP app using SHA-256

### ISSUE THREAD

**Issue by 962557346** [MicrosoftDocs/windows-driver-docs#2921]
Hi!
I am trying to get a SCCD file for my UWP app using the custom capability. The UWP is generated from the Unity, and I need to deploy the UWP from Visual Studio 2019 to HoloLens 2. [The document](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/hardware-support-app--hsa--steps-for-app-developers#contact-the-custom-capability-owner) indicates that I need to gather the PFN (Package Family Name) and Signature Hash of the app using SHA-256 to request access a custom capability. I have gotten the PFN. But I don't know how to get the Signature Hash of the app using SHA-256, because the Visual Studio 2019 directly deploys the app to the HoloLens 2.
I really appreciate any help you can provide.

**Comment by mhopkins-msft** [comment]
Hi @962557346

Is your app a hardware support app? The article you linked to is very specific to that type of app.

It sounds like you have questions about developing the app rather than feedback about the documentation. You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)

Again, thanks for reaching out. Best of luck with this issue.

 ~ *Mark*
