### ISSUE TITLE
Why does umdh.exe not detect BSTR-Leaks in x64 builds, contrary to x86 builds

### ISSUE THREAD

**Issue by stiffsen** [MicrosoftDocs/windows-driver-docs#3006]
I've had great success in finding memory leaks via GFLAGS and UMDH. However, I just discovered that UMDH somehow does not see BSTR-Leaks in 64 bit applications, whereas it does for 32 bit applications. Why is that? Is it a bug in UMDH x64, or maybe a change in how the Heap-Manager works for x64 applications? Is there a way at all to find COM-Leaks in x64 applications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8240b7f3-d4f1-4f59-a02e-3a22cb713b13
* Version Independent ID: 9b005c38-3997-72a9-9437-38a9b27640c9
* Content: [Using UMDH to Find a User-Mode Memory Leak - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-umdh-to-find-a-user-mode-memory-leak)
* Content Source: [windows-driver-docs-pr/debugger/using-umdh-to-find-a-user-mode-memory-leak.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/using-umdh-to-find-a-user-mode-memory-leak.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@stiffsen - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

It may be a combination of how the app was compiled and is being run and how the debugger is treating it's bitness (32/64). I would check the WOW64 debugger load settings as well as review, Choosing the 32-Bit or 64-Bit Debugging Tools - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/choosing-a-32-bit-or-64-bit-debugger-package. 

Because memory leaks are multicausal, I don't think there is yet a single tool that works across multiple environments to track them down.  In the general pursuit of memory leaks, you could explore the following: 

- AppVerifier > https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier
- The memory profile tools in Visual Studio https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?view=vs-2022
- If it is a C++ App there are specific settings - https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022
- The newer CodeQL tool set, which does have some setup to get working: 
  > https://codeql.github.com/codeql-query-help/cpp-cwe/
  > https://codeql.github.com/docs/

As you mentioned, it may also be a behavior of heap manager and some combination of the compile settings for a specific app.

For additional questions, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with tracking down COM memory leaks.
