### ISSUE TITLE
"DriverSetup" is not a registered WDTF system interface name

### ISSUE THREAD

**Issue by s0gray** [MicrosoftDocs/windows-driver-docs#3010]
uring testing driver for Windows Certification programm I got an error in tests "DF - Reinstall with IO Before and After"

WDTF_TARGET : ERROR : "DriverSetup" is not a registered WDTF system interface name. Win32=2 - The system cannot find the file specified.

It looks like WDTF can not reinstall driver due to missing interface. We use preinstalled image with HLM Studio and installed client as described: \\HLKInstall\Client\Setup.cmd.

Test PC OS: Windows 10 Home

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a940f18-8255-ae26-921c-1c4520e62738
* Version Independent ID: 5dc86be7-b7fe-5b4c-c711-f4ad02a857ad
* Content: [Extending the Framework - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdtf/extending-the-framework)
* Content Source: [windows-driver-docs-pr/wdtf/extending-the-framework.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdtf/extending-the-framework.md)
* Product: **windows-hardware**
* Technology: **wdtf**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@s0gray - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html).  

I'm not aware of an easy way to determine the root cause of the issue that you are experiencing. To validate that the issue is with the driver code, you could consider using the toaster driver to see how it works with the test - https://github.com/microsoft/Windows-driver-samples/tree/master/general/toaster/toastDrv

Then you could enable WDTF tracing in both drivers as described in https://docs.microsoft.com/en-us/windows-hardware/drivers/wdtf/viewing-wdtf-traces, and see at what point in the trace logs things diverge or fail. 

There may be a more efficient way to determine the cause, perhaps someone on the WDK DL will have a better idea then this suggested procedure. Good luck with your HLK test troubleshooting.
