### ISSUE TITLE
Is GFLAGS Idempotent and Persistent?

### ISSUE THREAD

**Issue by JonathonAnderson** [MicrosoftDocs/windows-driver-docs#3016]
Could you add something to this page regarding whether running gflags is idempotent and whether it survives an app pool recycle or a whole system reboot? We're trying to catch an intermittent problem that can occur as far as a couple weeks apart, which will definitely see app pool recycles and potential reboots for updates. If it's idempotent, I can just set our configuration management system to run the command on every scheduled run.

Edit: I meant to say originally, we're specifically using the pageheap functionality by running `gflags /p /enable w3wp /full`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3c9586-278a-096c-a42e-0ab771ca05a7
* Version Independent ID: 2f49821e-797f-668b-fd83-f096f79098a3
* Content: [GFlags - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags)
* Content Source: [windows-driver-docs-pr/debugger/gflags.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/gflags.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@JonathonAnderson - Thanks for this input on this docs page. We use input like this to guide the work that we do. As it turns out the GFlags persistence of settings story is a bit more complicated, so I don't think it is possible to make a single statement on this page. As you may have seen, the first topic linked from this page,  [GFlags Overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-overview), describes the different types of gflag settings, for example Kernel flag settings.  Using this topic and the information in [GFlags Flag Table](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-flag-table), you can investigate which flags will persist. If a test machine is available, you can use it to determine if options that you are using across reboots, by using the UI, command line or debugger gflag commands after a reboot. For assistance in determining which of the options that you are using persist across reboots, or pool cycles, you could consider the developer community forums, such as [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). Good luck in enabling the options you need to determine the app pool usage issues that you are working on.
