### ISSUE TITLE
The Driver Flighting video shows "Video unavailable" - appears broken.

### ISSUE THREAD

**Issue by SteveD-Eco** [MicrosoftDocs/windows-driver-docs#3035]
Something's wrong with the video on this page: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/driver-flighting: 

![image](https://user-images.githubusercontent.com/52679173/152618560-2d054cce-39f6-4d1a-aab9-bbccaa624be0.png)

**Comment by mhopkins-msft** [comment]
Hi @SteveD-Eco 

Thank you for reporting this. Unfortunately, this video was removed when Channel 9 was taken down. We're working on getting some of the videos restored, including this one. For now, I've removed the video from the article.

However, I did find that someone shared the video on YouTube here: https://youtu.be/4AnguNhq8FE

Since this YouTube channel is not owned by Microsoft, I'm reluctant to add this link to the article. If or when we get the video restored to a site owned by Microsoft, I will re-add it back into the article.

Thanks again for bringing this to my attention.
 ~ *Mark*
