### ISSUE TITLE
Does amli debugger support local debug?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#3038]
I am trying to do ACPI debug on Windows 11 22000.493 with local debugger. I ran !amli set dbgbrkon first. Then when I run !amli debugger. The system crashed. I also tried to set breakpoint on some AML method. It crashed too when the breakpoint was hit.

SYSTEM_THREAD_EXCEPTION_NOT_HANDLED (7e)
This is a very common bugcheck. Usually the exception address pinpoints
the driver/function that caused the problem. Always note this address
as well as the link date of the driver/image that contains this address.
Arguments:
Arg1: ffffffff80000003, The exception code that was not handled
Arg2: fffff80381e1e8c8, The address that the exception occurred at
Arg3: ffffa78a86748d48, Exception Record Address
Arg4: ffff8281ee5c3900, Context Record Address

Does amli debugger support local debug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43f880a4-34c0-29f7-f6aa-0754c690853a
* Version Independent ID: dc97dd43-ed9c-6b9f-a9ba-9663c398d4cb
* Content: [amli debugger - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-amli-debugger?source=docs)
* Content Source: [windows-driver-docs-pr/debugger/-amli-debugger.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-amli-debugger.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@guliteb - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

In general, anything as low level as ACPI and early boot debugging, is best performed using two systems, so that would be the recommendation.
