### ISSUE TITLE
dt dxgkrnl!_TDR_RECOVERY_CONTEXT BUT not found

### ISSUE THREAD

**Issue by sculida** [MicrosoftDocs/windows-driver-docs#3070]
[Enter feedback here]
Here is a memory.dmp which code is VIDEO_TDR_FAILURE
[memory.dmp.zip](https://pan.ruijie.com.cn/share/c53e6f2eb4a68057f6afc6f467)
I opened it from windbg, but while I write dt dxgkrnl!_TDR_RECOVERY_CONTEXT, it told me
**Symbol dxgkrnl!_TDR_RECOVERY_CONTEXT not found**
I had scanned each function, struct by dt dxgkrnl!*, but there was no one named RECOVERY_CONTEXT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367e4ff4-f83e-b642-095b-27769fb05505
* Version Independent ID: 24848013-3432-4ae4-8ffd-b664aefdd069
* Content: [Bug Check 0x116 VIDEO_TDR_FAILURE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x116---video-tdr-failure)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x116---video-tdr-failure.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x116---video-tdr-failure.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@sculida -This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
You could consider the use of !sym noisy to see if there is an issue with loading symbols for this version of Windows. It is also possible that the failure context is not present in the dump that was created. If you have multiple dumps you could check those, as well as investigate expanding the information stored when a dump occurs.
Your best bet to further investigate this, is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with determining the root cause of your 0x116.
