### ISSUE TITLE
reference to missing switch in poolmon.exe

### ISSUE THREAD

**Issue by nbalisciano** [MicrosoftDocs/windows-driver-docs#3083]
The page refers to using the /c switch, but that doesn't seem to exist for poolmon.
The command line reports: Poolmon: unknown switch: c
See also: https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon-run-time-commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5a6493-4db5-8f3f-9225-326db228bfbc
* Version Independent ID: 59d43335-d46e-44ef-fa22-e0a96e250138
* Content: [PoolMon Examples - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon-examples)
* Content Source: [windows-driver-docs-pr/devtest/poolmon-examples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/poolmon-examples.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@nbalisciano - As it turns out the /c switch is still available in the 32 bit version of poolmon. I updated the topic to better emphasize, that this is not available in the 64 bit version. At some point I may remove this 32 bit example, but as it may be useful in some situations, I will leave this reference to /c in the topic, at least for now. Thanks for pointing this issue out, and good luck with your use of poolmon.
