### ISSUE TITLE
Correct the description of known issues

### ISSUE THREAD

**Issue by kemyeh** [MicrosoftDocs/windows-driver-docs#3117]
[Enter feedback here]
For "Before you test selective suspend for a SuperSpeed hub, you should perform the following steps to disable selective suspend." should be "Before you test USBLPM for a SuperSpeed hub, you should perform the following steps to disable selective suspend."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c54b0295-17fc-5383-05d6-f3203cb95008
* Version Independent ID: 46a5d9cd-a055-5c2f-1d58-078d2b743510
* Content: [USBLPM - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usblpm-tool)
* Content Source: [windows-driver-docs-pr/usbcon/usblpm-tool.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usblpm-tool.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @kemyeh,

Thank you for bringing this to my attention.

I believe this issue is resolved by your pull request: [Update usblpm-tool.md #3116](https://github.com/MicrosoftDocs/windows-driver-docs/pull/3116). I have merged that pull request and it should be published today. Thank you so much for helping to make our docs better!

Sincerely,
 ~ *Mark*
