### ISSUE TITLE
nvlddmkm.sys error caused blue screen everytime i update my gpu in device manager or try download from hp or nvidia 

### ISSUE THREAD

**Issue by jereytucker** [MicrosoftDocs/windows-driver-docs#3180]
# #nvlddmkm.sys error caused blue screen everytime i update my gpu in device manager or try download from hp or nvidia

**Comment by lorihollasch** [comment]
Hi @jereytucker, I'm closing this issue as it is not documentation-related (this is a doc repo for Windows driver developers). I did a quick internet search and found [a relevant article](https://www.technewstoday.com/fix-nvlddmkm-sys-error-in-windows/) that might help you. Otherwise, I encourage you to reach out to [NVIDIA's customer support](https://www.nvidia.com/en-us/support/). Hope you are able to resolve your issue quickly.
