### ISSUE TITLE
How is the bthkd extension library used under WinDbg? 

### ISSUE THREAD

**Issue by 2tilted** [MicrosoftDocs/windows-driver-docs#3226]
I am trying to use the `!bthtree` command to dump the complete Bluetooth device tree as specified from the `!bthhelp` command.
WinDbg is running and is attached to a svchost.exe process that imports several Bluetooth DLLs:
- svchost.exe (1808) | DLL | C:\Windows\System32\bthserv.dll
- svchost.exe (1808) | DLL | C:\Windows\System32\BthTelemetry.dll
- svchost.exe (1808) | DLL | C:\Windows\System32\Microsoft.Bluetooth.Service.dll
- svchost.exe (1808) | DLL | C:\Windows\System32\Microsoft.Bluetooth.Proxy.dll
- svchost.exe (1808) | DLL | C:\Windows\System32\Windows.Internal.Devices.Bluetooth.dll

Using the `!bthkd.bthtree` command results in the following message:

`Controller:
Failed to read list of device objects.`

`BTHENUM:
Error: Unable to read BTHENUM!BthEnumGlobals
Unable to find driver object`

`RFCOMM:
00000000: Unable to get value of ObpRootDirectoryObject
Error: Unable to read rfcomm!g_DriverObject`

`ENUMERATED DEVICES:
Error: Unable to read BTHENUM!BthEnumGlobals
Unable to find driver object`

Sadly the other `!bthkd` commands (such as `!hcicmd`, `!bthenuminfo`) also fail in a similar manner.  WinDbg is debugging the target process locally.
Unfortunately, the documentation ([bthkd](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bluetooh-extensions--bthkd-dll-)) does not really provide much additional information on how to use the bthkd extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa864a4-dbd7-be14-93a4-8ad92770ca3c
* Version Independent ID: 72587dc4-e98f-f410-544f-e00dc8114375
* Content: [Bluetooth Extensions (Bthkd.dll) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bluetooh-extensions--bthkd-dll-)
* Content Source: [windows-driver-docs-pr/debugger/bluetooh-extensions--bthkd-dll-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bluetooh-extensions--bthkd-dll-.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@2tilted - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

It is possible that point that you have broken with the kernel debugger, the memory associated with the Bluetooth drivers is paged out or otherwise not in scope. This is described in [Changing Contexts](https://docs.microsoft.com/windows-hardware/drivers/debugger/changing-contexts). The solution there is to set a breakpoint so that the debugger has the desired driver object are in scope.  A general technique for locating and setting a breakpoint is described in [Debug Windows Drivers - Step by Step Lab (Echo Kernel-Mode)](https://docs.microsoft.com/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-).  Good luck with your use of the Bluetooth kernel debugging extensions.
