### ISSUE TITLE
-flt flag can't be used in windbg

### ISSUE THREAD

**Issue by Zossin** [MicrosoftDocs/windows-driver-docs#3276]
[Enter feedback here]

I tried to use below command in windbg to list allocations with specified size, but got failure:

    0:000> !heap -flt s 80

    HEAPEXT: !heap invalid option flag '-l'

Could you help let me know what's wrong here and how I can be unblocked?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9e90c35-9fc6-4b94-1ddd-73539af3a86d
* Version Independent ID: fa14c946-421a-e1f2-1a56-9777b14a4bde
* Content: [heap (WinDbg) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/-heap)
* Content Source: [windows-driver-docs-pr/debugger/-heap.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-heap.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Zossin - I did a quick test and had some issues as well with the -flt option of the !heap command, with the latest version of the WDK and Windows 11. To provide feedback to the debugger team on the !heap extension, follow this link to file product feedback using the debugger team product issue git hub:  

http://aka.ms/dexex

Here are some options for you to consider as work arounds.

- You can use the -s option, like `!heap -s -h <address> -a -d <block size>` for both NT and segment heap.

- You can search physical memory using the [!search]( https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/-search) command.

- If you are working with user mode, there are two additional options to explore. Time travel [TTD Heap Objects]( https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-heap-objects) and the [User-Mode Dump Heap (UMDH) tool](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/umdh).

- It looks like there may be two versions of the !heap extension. You can search for them like this `.extmatch /e ext* heap`

And use them by including the dll that you are interested in working with, like this.

```
!ext.heap -? 

!exts.heap -?
```

- Depending on what OS you are working with, if might be possible to download an older version of the debugger that may not have this issue.

You may also want to check with the [OSR's windbg List](https://community.osr.com/categories/windbg) and see if there are other strategies to accomplish what you need to with heap memory. I hope this helps provide some ideas for work arounds instead of using the -flt option of !heap.
