### ISSUE TITLE
windows hardware developer->hardware dashboard API->update a shipping label.

### ISSUE THREAD

**Issue by HaraldWang** [MicrosoftDocs/windows-driver-docs#3296]
[Enter feedback here]
i have a useing problem in windows hardware developer->hardware dashboard API->update a shipping label.
API URL:
https://manage.devcenter.microsoft.com/v2.0/my/hardware/products/{productID}/submissions/{submissionId}/shippingLabels/{shippingLabelId}
i want to konw how to write the request body.  i have already published a shipping label an its already finish. now i want to delete restrictedToAudiences info to publish it again. the following info is the request body:
{
  "targetingInfo": {
    "restrictedToAudiences": [
      ],
    "businessJustification": "Business justification for updating shipping label"
  }
}

but i got something wrong:
{
    "error": {
        "code": "invalidInput",
        "message": "Validation Failed.",
        "validationErrors": [
            {
                "target": "targetingInfo.chids",
                "message": "At least one property is required for update."
            },
            {
                "target": "targetingInfo.hardwareIds",
                "message": "At least one property is required for update."
            },
            {
                "target": "targetingInfo.restrictedToAudiences",
                "message": "At least one property is required for update."
            }
        ]
    }
}
then i added some info about chid and hardwareId, but i still got this problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68b9e39f-a269-82bb-d44a-162ed96fab57
* Version Independent ID: 03adbc66-9e14-11b0-407b-a2d4b09ee7b5
* Content: [Update a shipping label - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/update-a-shipping-label#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/update-a-shipping-label.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/update-a-shipping-label.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
@HaraldWang I am looking into this for you now. In the meantime, take a look at https://github.com/MicrosoftDocs/windows-driver-docs/issues/1438.  It's an issue from 2019 that seems to suggest that you should use Targeting instead of TargetingInfo. I'm not certain that will solve your problem, and so I will continue to look for more information. In the meantime, let me know if that solves your problem.

**Comment by HaraldWang** [comment]
the solution above i will try later and i will give you the reply, thanks.

**Comment by anaharris-ms** [comment]
Closing out due to inactivity.  Please reopen if still needed.  Thanks for reaching out!

**Comment by HaraldWang** [comment]
@anaharris-ms hi，sorry for long time with no reply, our project for some reason was delay. I tried the method mentioned in issue [#1438](https://github.com/MicrosoftDocs/windows-driver-docs/issues/1438).  the request and response like the picture below:
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/46599197/35318799-3493-4803-9a46-ffd5b99d05f8)

I just want to delete the value in field [restrictedToAudiences], and other infos remain unchanged.

**Comment by anaharris-ms** [comment]
Hi @HaraldWang ,

Sorry to hear you are still having trouble. Have you tried contacting customer support: https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues?

**Comment by HaraldWang** [comment]
you mean i have to create a new issue?

**Comment by ltproject** [comment]
Anaharris
it looks like this was mistakenly left under MY COMPUTERS FEEDBACK SUBMISSION. I am the owning user. I think I'm listed as Sarahsmom. Those shipping labels....my shipping labels. What is the purpose of this complete life altering infiltration of any and all devices that I own. I,being a single Mother with no family except my nine year old. Who is just trying to life my life and provide for my child which you all at github and Microsoft make impossible. Is it just because you have been doing it for so long that the projects have more value than just   trial and error info? You look like a young woman. There is a person behind the ip address. a face that goes with the limited admin rights user. What is this doing to my nine year old in the long game? this has been going on since before she was born. I can't even go to my kids parent portal to her school.  Just know that i write down every name I can. Yours just got added.
