### ISSUE TITLE
Placeholder information found its way to the public documentation :)

### ISSUE THREAD

**Issue by scaramushe** [MicrosoftDocs/windows-driver-docs#3338]
[Enter feedback here]
Looks like below section should not be publicly visible :):

```
The hashing function can be one of the following:

NdisHashFunctionToeplitz
**NdisHashFunctionReserved1
NdisHashFunctionReserved2
NdisHashFunctionReserved3**

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9e232cb-5644-66ee-2f99-68891d198055
* Version Independent ID: 17f242e2-1aa3-c06e-986f-6407930616b0
* Content: [RSS Hashing Functions - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/rss-hashing-functions)
* Content Source: [windows-driver-docs-pr/network/rss-hashing-functions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/rss-hashing-functions.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @scaramushe, Thanks for opening this issue. The reserved hash functions are actually in the public header (hashtypes.h), so the author of this topic decided to list them all and include a warning note below that:
Currently, NdisHashFunctionToeplitz is the only hashing function available to miniport drivers. The other hashing functions are reserved for NDIS. 
Since there is a note of clarification, we won't update the topic at this time. Please open a new issue if you have further comments or questions.
Thanks again.
