### ISSUE TITLE
But how to you connect to a Bluetooth Personal Area Network?

### ISSUE THREAD

**Issue by TBemrose** [MicrosoftDocs/windows-driver-docs#3341]
[Enter feedback here]
But _HOW_ do you create / connect to a Bluetooth Personal Area Network in Windows 11? This page says it's possible, but no page anywhere says how.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27a0ed90-dff4-f356-1853-de669b0d1540
* Version Independent ID: d846c2ad-9b05-8e61-45f0-19e50734f0f3
* Content: [Bluetooth version and profile support in Windows 11 - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bluetooth/general-bluetooth-support-in-windows)
* Content Source: [windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md)
* Product: **windows-hardware**
* Technology: **bluetooth**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @TBemrose,

Thanks for reaching out to us. This article is intended to inform Windows device driver developers about the Bluetooth profiles available in Windows 11 so they can create drivers that work with their Bluetooth devices. 

A quick web search led me to several solutions, including this third-party article about **[Creating a Bluetooth personal area network](https://sourcedaddy.com/windows-10/creating-bluetooth-personal-area-network.html)** in Windows 10. Following the steps, I was able to create a personal area network between two computers and copy a file using Windows 11.

Since this is not a Microsoft article I can't officially recommend it, nor can I offer further support. But as I said, it worked for me. If you have further questions, please contact **[Windows support](https://support.microsoft.com/windows)**.

Best of luck,
 ~ *Mark*
