### ISSUE TITLE
Ctrl + F4 does not close a window on windows 11 on my pc

### ISSUE THREAD

**Issue by ThakurSaad** [MicrosoftDocs/windows-driver-docs#3423]
I tried pressing `ctrl + F4` simultaneously. But it does not close an open window in my **windows 11**. 

Then I pressed `alt + space` to look for details and found the command is `alt + F4`. So, `alt + F4` is the command to close a window on my PC. You can see it in the top left corner of the image. 

![image](https://user-images.githubusercontent.com/96883294/222144796-b0115663-5581-4be8-9688-a5663be1085b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0a8eabb-8318-eb48-8198-9b1c3466b491
* Version Independent ID: 38b05d0e-1988-f857-490a-71b99df58365
* Content: [Closing a Window - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/closing-a-window)
* Content Source: [windows-driver-docs-pr/debugger/closing-a-window.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/closing-a-window.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ThakurSaad - Thanks for the interest in the Windows Debugger (WinDbg) documentation. As it turns out, this topic is specific to the Windows debugger tool - WinDbg, and not intended to apply to Windows 11. I will look at what I can do to this topic to better clarify that this is just for the debugger. Thanks for passing on what you are seeing, as you use Windows.
