### ISSUE TITLE
Suggestion to edit the article (work around to resolve this issue)

### ISSUE THREAD

**Issue by prafulbusa** [MicrosoftDocs/windows-driver-docs#3462]
We know this issue is due to registry causing some boot issue but we don't know exactly what and that's where we can try to use the old registry if there is saved on the OS disk in order to put it back using the recovery environment. After that, you might be able to login in the VM (VM starts working after that) and boot without issue. 

But if you try just safe mode or advance boot menu options to start VM using the last known good config without using the old working registry, then your machine won't even boot in any of those options. 

So, hopefully you have it saved somewhere, then you get back to your business without worry' 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0472ee49-5ec9-315d-1e52-47605fef039b
* Version Independent ID: ea54ca27-fb2a-be87-7516-ec51083b92c8
* Content: [Bug Check 0x69 IO1_INITIALIZATION_FAILED - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x69--io1-initialization-failed)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x69--io1-initialization-failed.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x69--io1-initialization-failed.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@prafulbusa - Thank for passing on what you are seeing, and it does seem possible that the registry could contain information that would impact the boot process. I'm checking with the dev team to see if we can expand what is documented for this bug check code. As the crash dump file does not contain much information, this can be a difficult bug check to root cause. This Microsoft answer forum describes the use of "Repair your computer" and "Bootrec /RebuildBcd" which seem like logical troubleshooting steps.

https://answers.microsoft.com/en-us/windows/forum/all/getting-blue-screen-error-io1initializationfailed/23d9a677-dd0d-4c0a-928a-690d8c5582d2

These forums are a good place to pass on information and tips that you find. For example, this one is used for Windows Hardware.

https://learn.microsoft.com/en-us/answers/tags/384/windows-hardware-performance

Good luck with debugging this failure in Windows initialization.
