### ISSUE TITLE
Building arm64 sfloppy example doesn't work as expected.

### ISSUE THREAD

**Issue by ryantheleach** [MicrosoftDocs/windows-driver-docs#3478]
https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/building-arm64-drivers.md

The instructions here do not work.

Attempting to do this with the sfloppy example from https://github.com/microsoft/Windows-driver-samples/tree/46db93c4c0542166457f5504010b402a9426ab1d/storage/sfloppy

Results in the following error:

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not s
et for project 'sfloppy.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform
='Arm64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exis
t for this project. [D:\JanusCycleDriverBuild\Windows-driver-samples\storage\sfloppy\src\sfloppy.vcxproj]

Note that the error is occuring in amd64, not arm64.

I believe there is more changes to be made in order to recompile WDM drivers, but not sure what they are yet.

**Comment by barrygolden** [comment]
@ryantheleach, thanks for filing an issue on the instructions for configuring a driver for ARM64 builds

There are several things potentially happening here. 

(1) You should probably use the solution file (sfloppy.sln) to access the sample in Visual Studio. The ARM64 configuration settings will create some entries in sfloppy.sln.

(2) Be sure that you have installed the **MSVC v143 - VS 2022 C++ Arm64 Spectre-mitigated libs (Latest)** or equivalent for your Visual Studio version as outlined in [**Step 1: Install Visual Studio 2022**](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-1-install-visual-studio-2022) of the **Download the Windows Driver Kit (WDK)** topic.

(3) The sfloppy driver sample is quite dated, and though still in the Windows-driver-samples repo **main** branch, it has been removed from the **develop** branch and has been moved to an archive branch (see https://github.com/microsoft/Windows-driver-samples/commit/800278d3a66158b2f0f7eb6e9ce880bedb54def3).

(4) While attempting to build the driver for x64, I ran into multiple errors.  The first error calls out that the following needs to be added in the [Version] 

`PnpLockdown=1`

There are also 14 deprecated ExAllocatePoolWithTag function calls that are warnings but are treated as errors due to the default /WX complier setting.  Removing the /WX setting and changing to the /W3 warning setting gets past those errors. The build output shows a sfloppy.sys message:

`1>sfloppy.vcxproj -> C:\sfloppy\src\x64\Debug\sfloppy.sys`

but the file does not appear in the Debug build folder and the build fails more errors starting with:

`error MSB4018: The "SignTask" task failed unexpectedly.`
`error MSB4018: System.Security.Cryptography.CryptographicException: Access is denied.`

and so on.

However, at this point I was able to complete the ARM64 configuration per the instructions in the [Building Arm64 Drivers with the WDK](https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/building-arm64-drivers).

![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/15650191-8e5a-4ec1-bc1b-5d8be20e0c01)

But again, the ARM64 build failed with the same SignTask errors as the x64 build. At this point, it looks like the ARM64 configuration instructions in the topic are viable, but obviously the sfloppy sample is not.

I'd suggest that you try additional driver samples to see if you can build an x64 driver, then try the instructions for the ARM64 configuration.

You can also post questions about build errors in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
