### ISSUE TITLE
BFS filter at altitude 150000 not registered

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#3490]
Lori, Ted,

I was poking about a Win11 22H2 install today and I spotted this:
```
C:\Windows\System32> fltmc instances
...
bfs                   C:                                        150000     bfs                       0     0000000f
```
Newly flighted filter drivers can often cause me interop problems so this picqued my interest.  But nothing immediately pops out about it from a quick search (unless it's the [ABFS](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver) ?)

So, going to this page I find that not only it is not registered, it runs at an altitude (15000) which is not even allowed - between "160000 - 169999: FSFilter Compression" and "140000 - 149999: FSFilter Encryption"

I'm not convinced that having this filter documented will help me if it causes me interop issued, but at least knowing what it is meant to do might help.  Also to know what can possibly go between Compression and Encryption ?

Thanks!  Stay safe

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2d558e-1073-85d5-f863-5bdbf6e3ddc6
* Version Independent ID: 62e4d735-803f-7608-154b-7032dc1ceb3d
* Content: [Allocated filter altitudes - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes)
* Content Source: [windows-driver-docs-pr/ifs/allocated-altitudes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/allocated-altitudes.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @rodwiddowson , sorry for my slow response - it took a while to get to the bottom of this mystery. It turns out that "bfs" (brokering) is a Microsoft filter introduced to the system by a team that was unaware of the altitude request policy, sorry! They have submitted a request for an official number, but I think that number won't be adopted until the next big release of Windows (probably sometime next year). The team is looking at moving bfs into the 100000-109999 FSFilter Open File range, FYI. Hope you are doing well!
