### ISSUE TITLE
KeReleaseSemaphore with the Wait parameter set to TRUE

### ISSUE THREAD

**Issue by alex085** [MicrosoftDocs/windows-driver-docs#3493]
There is a confusing paragraph here

_"A pageable thread or pageable driver routine that runs at IRQL PASSIVE_LEVEL should never call KeReleaseSemaphore with the Wait parameter set to TRUE. Such a call causes a fatal page fault if the caller happens to be paged out between the calls to KeReleaseSemaphore and KeWaitXxxObject(s)."_

What does it mean "_**caller** happens to be paged out_"? Code and even stack could be paged out if the dispatcher switches the current thread between calls to KeReleaseSemaphore and KeWaitXxxObject. What is the problem of paged out code (and even stack) if the thread is not executing at that moment?

For example, in Windows-driver-samples there is a sample [Cancel-Safe IRP Queue](https://github.com/microsoft/Windows-driver-samples/blob/main/general/cancel/sys/cancel.c#L770). You can see a call to KeReleaseSemaphore with the Wait parameter set to TRUE and then a call to KeWaitForSingleObject.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ead1f82-a442-2853-6aca-25f04e2bbee8
* Version Independent ID: 9a4a93ff-fe07-78d3-81c5-2f06d18bd68a
* Content: [Semaphore Objects - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/semaphore-objects)
* Content Source: [windows-driver-docs-pr/kernel/semaphore-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/semaphore-objects.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @alex085 for the feedback.  The sample you link to appears to be buggy since it marks CsampUnload as pageable -- we're now tracking this internally.

It turns out that clearer info is in the Remarks section of https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kereleasesemaphore, so I moved and slightly updated the paragraph you provide above to this page, and formatted it as a warning.  See specifically the Warning and the two paragraphs before it.

I linked to this (and mentioned the Remarks specifically) from https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/semaphore-objects (third paragraph from the bottom).

Thanks again for caring about the docs!
