### ISSUE TITLE
Multiple printer driver tutorial errors, tutorial is not usable

### ISSUE THREAD

**Issue by JC3** [MicrosoftDocs/windows-driver-docs#3575]
Multiple errors in V4 printer driver tutorial.

Some errors include:

- In *Create a unique PrinterDriverID for the driver*: The *Driver Files* property pages are blank, there is no *Unique Identifier* field. The step cannot be completed.
- In Step 6: The *Driver Files* property pages are blank, there is no *Unique Identifier* field. The step cannot be completed.
- In *Add the Pipeline Config file to the driver package*: The *Driver Install* configuration section does not have a *Package Files* page. The step cannot be completed.
- In *Configure the driver solution for debugging and deployment*: The *Driver Install* configuratoin section does not have a *Deployment* page. The step cannot be completed.
- In *Test the driver*: The resulting driver is not installable. The Add Printer (Manual Settings) wizard states "Printer driver was not installed. A problem was encountered while attempting to add the driver to the store." So the tutorial's output is not a functional driver. No details are provided about the error.

#### VS Info

```Microsoft Visual Studio Community 2019
Version 16.11.27
VisualStudio.16.Release/16.11.27+33801.447
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-00000-00000-AA139
Microsoft Visual C++ 2019

Azure App Service Tools v3.0.0   16.11.115.10959
C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Common Azure Tools   1.10
Debugging Tools for Windows   10.0.19030.1000
IntelliCode Extension   1.0
Markdown Editor   1.12.253
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual C++ Wizards   1.0
Microsoft Visual Studio VC Package   1.0
MLExtension   1.0
NuGet Package Manager   5.11.4
ProjectServicesPackage Extension   1.0
Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools for Unity   4.11.4.0
Windows Driver Kit   10.0.19030.1000
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceb38-396a-aa19-6304-be3df9b0ca08
* Version Independent ID: 2f34593f-aa20-384a-b1bb-c8a962ec4706
* Content: [Build a basic v4 printer driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver)
* Content Source: [windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md)
* Product: **windows-hardware**
* Technology: **print**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@JC3, thanks for filing an issue with the Windows driver documentation team on the errors you found in the **Build a basic v4 printer driver** tutorial. I've verified several of the errors you found in the article and will address them below. I've added two alerts to the article: 

1. The recommendation that print driver developers use Microsoft's IPP inbox class driver, along with Print Support Apps (PSA), to customize the print experience in Windows 10 and 11 for printer device development. For more information, see the [Print support app design guide](https://learn.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide).

1. A warning that the v4 print driver tutorial contains multiple errors and is not usable at this time.

![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/b32d5af4-db2c-4360-bd8d-cf2c0b760d53)

Regarding the errors you found, I was able to verify your first and second bullet points above that the **Driver Files** property pages are blank as shown here:

![Driver_Files_Property_Pages](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/36ea552e-a063-483a-b36a-ca44a0019772)

As a potential workaround, I copied the GUID I generated with the **Create GUID** tool to a text file and then added it to the `[Standard.NT$ARCH$]` section of the _MyV4PrintDriver.inf_ file during step **6. Add the PrinterDriverID to the INF file**:

`"Fabrikam 1234"=Driver Install, {FB8D69D5-BB6F-4730-94AE-F25997FCED76}`

As to your third bullet point above, I was able to access and complete the steps in **Add the Pipeline Config file to the driver package** using this property page:

![Configuration_Properties-Driver_Install-Package_Files](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/bc8aaffc-b4a2-4b62-b35c-ab246ba4fe1f)

Similarly, per your fourth bullet point, I was able to access and complete the steps for the **Deployment** page of the **Driver Install** section:

![Configuration_Properties-Driver_Install-Deployment](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/d29efd5e-b0a5-42d4-bc26-eaa8f0b6da09)

Unfortunately, I was unable to check the error message you call out in your final bullet point in the **Test the Driver** section, as the driver build failed in the prior **Build and deploy the driver** step with the following output:

![Build_Output](https://github.com/MicrosoftDocs/windows-driver-docs/assets/1238101/ddd99667-a73f-4942-9af1-21bb63a8f986)

I've been unable to resolve the build errors in the build output shown above.

I am in contact with the Print Platform development team to determine a root cause for these errors you found as well as those I found in the build output. 

I will reopen and update this issue when I have additional information on any potential workarounds or updated procedures for the tutorial.

Thanks again for providing detailed information on the errors you found in the article.
