### ISSUE TITLE
Lack of useful examples

### ISSUE THREAD

**Issue by pbhogale-12166972** [MicrosoftDocs/windows-driver-docs#3596]
Need a good example on how to use this syntax: **[models-section-name.TargetOSVersion]  (Windows XP and later versions of Windows)**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5833229-388e-d867-00cb-8845ab816f45
* Version Independent ID: f30a49f5-d5ea-36ea-3dde-86a9905cbd0c
* Content: [INF Models section - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/inf-models-section)
* Content Source: [windows-driver-docs-pr/install/inf-models-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-models-section.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for raising this, @pbhogale-12166972.  It turns out the info you want is in the docs, it was just harder to find than it should have been.  To address this, I just added a line at the bottom of https://learn.microsoft.com/en-us/windows-hardware/drivers/install/inf-models-section#examples that describes where you can find more examples.  Let me know if those examples address your questions.
