### ISSUE TITLE
Conflicting directions /analysis on Critical Section timeout analysis page

### ISSUE THREAD

**Issue by awaris** [MicrosoftDocs/windows-driver-docs#3604]
[Enter feedback here]
Hi, the article says:

"Continue tracing the chain of waits until either a loop is found or the final thread is not waiting for a critical section time out."

From the stack trace analysis, it finds that "Thread 21 has RtlpWaitForCriticalSection near the top of its stack. Thread 6 does not. So thread 21 is the culprit."

This should mean that thread 21 is waiting for a Critical Section while thread 6 is not, so thread 6 should be the culprit instead of thread 21. Am I correct ??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40a3474f-7cc9-1d5c-9889-bee7b368ba0f
* Version Independent ID: 07764aca-0675-0dfa-4aab-89aa654e3261
* Content: [Critical Section Time Outs - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/critical-section-time-outs)
* Content Source: [windows-driver-docs-pr/debugger/critical-section-time-outs.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/critical-section-time-outs.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@awaris - Thanks for this issue for this topic pointing out the open-ended description of which thread is the culprit. I updated the topic to better describe what you know as the point you have looked at thread 21 and 6. I think the term culprit is not right in that the threads shown, or possibly even another thread could be the root cause that of the timeout. So, I think the next step would be to look at the locking associated code for those two threads. I added information on the use of application verifier, which would be a valuable tool in digging further to determine the culprit in this case. I also added a reference to a code sample and example debugging session of an orphaned critical section, in Advanced Windows Debugging by Mario Hewardt and Daniel Pravat as another possible resource.  Thanks again for filing this issue, and good luck in your debugging work.
