### ISSUE TITLE
Performance Impact

### ISSUE THREAD

**Issue by GitFezz** [MicrosoftDocs/windows-driver-docs#3605]
Please comment on known, expected, or potential performance and/or storage use impacts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ffa53b4-9fd8-a6a0-684a-2d8250e8eaac
* Version Independent ID: a120f60f-95a4-6c18-cecf-38ec1fed4fb8
* Content: [WPP Software Tracing - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/wpp-software-tracing)
* Content Source: [windows-driver-docs-pr/devtest/wpp-software-tracing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/wpp-software-tracing.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@GitFezz - For performance I would take a look at [What is the performance cost of software tracing?](https://learn.microsoft.com/windows-hardware/drivers/devtest/what-is-the-performance-cost-of-software-tracing-). The design goal is to be as low impact as possible, but there are ways that performance can be impacted.
- If someone has written an incorrect logging provider. For example, by logging too much data, too frequently.
- If many things have been configured to be logged at the same time.
- If the OS is already low on swap space or available storage.
 
On storage, it is common to loop the log files so that they begin to overwrite, instead of infinitely expanding and consuming storage, although this can be mis-configured. For example, this overwrite behavior can be set under properties for items displayed in event viewer.

Each PC and app install profile may include a mix of efficient and inefficient logging, so it can take work to determine the impact of any additional logging.   

For additional questions in this area, I would recommend the Windows Hardware Performance Q&A forum - https://learn.microsoft.com/en-us/answers/tags/384/windows-hardware-performance
