### ISSUE TITLE
Update Microsoft Store description

### ISSUE THREAD

**Issue by MV10** [MicrosoftDocs/windows-driver-docs#3627]
> WinDbg Preview will not receive further updates in the Microsoft Store.

You should update the description of _WinDbg Preview_ in the Store to indicate that's an old version and won't be receiving updates.

Or better yet, remove it completely.

Then give us a simple ZIP installer for people who have to use this in corporate environments where Stores and installers are likely blocked by GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68be4f3a-a792-45da-3c43-533aed0f89b1
* Version Independent ID: 2cc4d72a-3053-6f06-8613-61e7a144e094
* Content: [Install WinDbg - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/)
* Content Source: [windows-driver-docs-pr/debugger/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/index.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MV10 - Thanks for this input on updating the store description, I passed it on to the dev team. 

Over on the Windbg feedback github site (http://aka.ms/dexex), there are directions to download and run a PowerShell script to install WinDbg. 

https://github.com/microsoft/WinDbg-Samples/issues/57

So that is one option. The dev team also is looking at other install options based on user input, to accommodate as many use cases as possible. 

Thanks again for providing this input, and good luck with your use of WinDbg.
