### ISSUE TITLE
There is a problem with the document

### ISSUE THREAD

**Issue by skrandy** [MicrosoftDocs/windows-driver-docs#3629]
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x3b--system-service-exception

Identify the driver
If a driver that is responsible for the error can be identified, its name is printed on the blue screen and stored in memory at the location (PUNICODE_STRING) KiBugCheckDriver. You can use [dx (display debugger object model expression)](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/dx--display-visualizer-variables-), a debugger command, to display this: dx KiBugCheckDriver.

The `dx KiBugCheckDriver` command is no longer available

Error details:
```
9: kd> dx KiBugCheckDriver
Type information missing error for KiBugCheckDriver
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: KiBugCheckDriver                              ***
***                                                                   ***
*************************************************************************
Error: Unable to bind name 'KiBugCheckDriver'
```

**Comment by DOMARS** [comment]
@skrandy - In my testing, the `dx KiBugCheckDriver` is functional, so I don't believe there is an error in the docs. Typically, the error output shown, indicates that the symbols are missing for that build of Windows on the symbol server that you are accessing. For more information about troubleshooting symbols, see [Symbol Problems While Debugging](https://learn.microsoft.com/windows-hardware/drivers/debugger/symbol-problems-while-debugging). The use of `!sym noisy` can be helpful in watching symbol loading.  Even with symbols being available for that version of Windows, it is very possible that the specific crash was not able to identify a faulting driver, so that information may not be present, or even corrupted.  For further assistance with troubleshooting 0x3B, you may have success posting your question in the following debugging forum.

[OSR's windbg List](https://community.osr.com/categories/windbg)
