### ISSUE TITLE
PnpUtil.exe does not provide source code as the DevCon.exe it replaces at https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon yet one of our factory drivers needs to on-the-fly install a driver so the src code to a supported PnpUtil is needed

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/windows-driver-docs#3670]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18777b73-5898-9e38-c074-5d5ec1572d80
* Version Independent ID: d08c4303-6dee-049a-1c69-620b5bcb68f9
* Content: [PnPUtil - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil)
* Content Source: [windows-driver-docs-pr/devtest/pnputil.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnputil.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
Thanks for the question @markyoung2u. 

We have no plans to release source code for Pnputil.  However, since it is present on every Windows machine, your install sequence can call it with confidence.  Or, depending on your specific scenario, you could alternatively call DiInstallDriver to install the driver programmatically.
