### ISSUE TITLE
Quirk when using Surface Pro 7+ as debug host

### ISSUE THREAD

**Issue by terrillmoore** [MicrosoftDocs/windows-driver-docs#3739]
[Enter feedback here]

When using a Microsoft Surface Pro 7+ as a USB debug host, I found that the USB cable must be attached to the type A port in the tablet itself. Connecting to a type-A port in a Microsoft Surface docking station did not work -- WinDbg would connect during boot, but it was impossible to break in. In both cases, things look fine in device manager.

This should be documented clearly, if it's a known restriction.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb75fe-9c66-7d5b-ae4f-0fe9b6745300
* Version Independent ID: bee2ac4a-b55a-5691-3773-c87d5bd3c9b2
* Content: [Set up kernel-mode debugging over a USB 3.0 cable - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@terrillmoore - Thanks for this input on the use of a cross over USB cable. I could see how a docking station or other active USB device could interfere or otherwise complicate setting up a debugger connection. I added a note to this topic and the USB 2.0 topic to connect directly. Thanks for your interest in the debugger docs, and good luck with your USB debugging work.
