### ISSUE TITLE
Hypervisor Firewalls

### ISSUE THREAD

**Issue by rhyspaterson** [MicrosoftDocs/windows-driver-docs#420]
If you're using a thrid party hypervisor, such as VMware ESXi, also ensure the hypervisor layer firewall allows these connectivity for VM to VM communication. Our ESXi firewall was blocking this which cuased headaches for many days:

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-09086DBC-FC86-4589-9B58-3310B2FB47A8.html

> Before you connect network-backed virtual serial ports, you must add one of the following firewall rule sets to prevent the firewall from blocking communication:
> 
> VM serial port connected to vSPC. Use to connect the serial port output through a network with the Use virtual serial port concentrator option enabled to allow only outgoing communication from the host. 
> VM serial port connected over network. Use to connect the serial port output through a network without the virtual serial port concentrator. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccedc354-3446-6927-e83d-331c2f24f81f
* Version Independent ID: b2b523dc-1a11-c39b-0466-6bc35410181f
* Content: [Setting Up Kernel-Mode Debugging of a Virtual Machine Manually](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/attaching-to-a-virtual-machine--kernel-mode-)
* Content Source: [windows-driver-docs-pr/debugger/attaching-to-a-virtual-machine--kernel-mode-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/attaching-to-a-virtual-machine--kernel-mode-.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@rhyspaterson - Thanks for the input on adding firewall troubleshooting. I updated the topic to include a new "Troubleshooting Firewalls and Network Access Issues" section. This section includes this text: 
_Your debugger (WinDbg or KD) must have access through the firewall. This can even be the case for virtual serial ports that are supported by network adapters._
Thanks again for this input to try and help the next person that is working to complete the VM setup, so that they can work on the actual debugging problem at hand.
