### ISSUE TITLE
Extend the document to include the parameters

### ISSUE THREAD

**Issue by theking2** [MicrosoftDocs/windows-driver-docs#435]
Frequent 0x74 bugchecks might not be the result of registry errors. It might instead be the result of the OS not being able to open SYSTEM registry  due to a wrong order of boot devices. I have at least one system that has frequent 0x74 bugchecks report failed repair attempts but than be able to boot again normally.
An elaboration of the parameters might help the user to repair the system manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fdc587-37f6-7dc7-0f7d-2ddc189a1123
* Version Independent ID: 5b82fd28-1d78-0f87-7605-fc5309e6d1cd
* Content: [Bug Check 0x74 BAD_SYSTEM_CONFIG_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x74--bad-system-config-info)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x74--bad-system-config-info.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x74--bad-system-config-info.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by duncanmacmichael** [comment]
Hi @theking2 , that's good feedback. We'll definitely take this into consideration and investigate the best way to update the topic. Just to let you know, the investigation process for updating bug check pages might take a while compared to other topics because we need to make sure we get the right info on the page. So, this change won't happen immediately but we have gotten the ball rolling. Thanks for your interest in improving the docs.
