### ISSUE TITLE
Add a little more

### ISSUE THREAD

**Issue by Soogbad** [MicrosoftDocs/windows-driver-docs#493]
Should have a little bit of information about what is a stack trace and how it looks like..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb8dfca-429b-5c71-c98d-5b07c6e562f1
* Version Independent ID: b476685e-1c4a-566e-9d04-3effd0196e83
* Content: [Viewing the Call Stack in Visual Studio](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/viewing-the-call-stack-in-visual-studio#span-idusingthecallstackwindowspanspan-idusingthecallstackwindowspanspan-idusingthecallstackwindowspanusing-the-call-stack-window)
* Content Source: [windows-driver-docs-pr/debugger/viewing-the-call-stack-in-visual-studio.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/viewing-the-call-stack-in-visual-studio.md)
* Service: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Soogbad - Thanks for this input on expanding the guidance we provide for call stacks in Visual Studio.
As this feature is not available in Windows 10, version 1507 and later versions of the WDK, we will not be able to prioritize this request, so that we can invest that time in currently supported features and products. Thanks for your interest in our documentation and for your feedback on this topic.
