### ISSUE TITLE
WFP Callout Drive rKernel Debugging over time leads to install errors and anomalies 

### ISSUE THREAD

**Issue by NoelStephens** [MicrosoftDocs/windows-driver-docs#673]
I have been running into some issues with the most recent Windows 10 update (July 2018) and Kernel Debugging tools from the 10.0.14393.0 WDK.  Originally, prior to the update and/or my (nth) debugging iteration (probably in the 100’s) when I install (right click the inf file and install) the newly installed driver no longer shows up when one uses an elevated command prompt and types “pnptuil -e”.  This used to be the case, but at this point it appears to require one to actually start the driver service before it shows up.  Taking the DDProxy example, this shows similar behavior patterns and no longer shows up under the device manager (i.e. enable show hidden) even when started.  
Is there a known “limit” of how many times one can install and uninstall (i.e. pnputil -d oem#.inf) a driver and/or if one gets a BSOD and resets before allowing the full dump file to be generated?  As well, it seems the longer one installs/uninstalls drivers on the host kernel debug machine the longer it takes to boot.   I am posting this in this area because it seems there should be more “troubleshooting” oriented information for callout drivers.  I have developed layer 2 NDIS drivers and never experienced this issues…only with WFP Callouts.  Can one no longer see a WFP callout in the device manager (if so perhaps this portion of the online documentation should be updated)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d0041dc-cda6-1301-029f-d952084aa661
* Version Independent ID: b2a4b4d0-6b88-1b6c-c957-d6c00bf34279
* Content: [Installation of Callout Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/installation-of-callout-drivers)
* Content Source: [windows-driver-docs-pr/network/installation-of-callout-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/installation-of-callout-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @NoelStephens , that's a good question. Let me ask the feature team to see what I can find out. You are right in that the driver developer docs aren't oriented towards troubleshooting, which is why we don't have dedicated troubleshooting pages in general, *but* if I can make the page clearer to help with development then I'd be more than happy to.

**Comment by duncanmacmichael** [comment]
OK, I have an answer about the device manager question. Starting in Windows 8 and later, callout drivers are not visible in Device Manger by design because the PnP manager doesn't create a device representation for them any more. I've updated the doc to reflect this information. If a callout does show in in Device Manger, it is likely because of an error in the INF file.

As for your questions about troubleshooting the `pnputil` command, I'm sorry but I don't have an answer for you there. I'd recommend checking out the WFP section of the [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk) forum. Or, perhaps the community at [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev) could help. They're quite responsive and knowlegeable about such issues.

Thanks again for the questions and for your interest in improving the docs.
