### ISSUE TITLE
Can I know the reason of this note?

### ISSUE THREAD

**Issue by wangmir** [MicrosoftDocs/windows-driver-docs#719]
Hi, I'm trying to develop ARM64 network device driver for WoA, and I have a question about this note. Can you specifically mention why ARM64 processors cannot use NDIS SG DMA? I think I have a problem with memory management at the device driver, so if I notice about this issue, it can be very helpful.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d28d347-3f57-6562-54c3-9355fa3b7493
* Version Independent ID: 629a62d6-72f0-3f85-0943-4f8a9aaa1e26
* Content: [Note to discourage NDIS DMA use on ARM/ARM64 processors](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-dma-arm-note)
* Content Source: [windows-driver-docs-pr/network/ndis-dma-arm-note.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/ndis-dma-arm-note.md)
* GitHub Login: @duncanmacmichael

**Comment by duncanmacmichael** [comment]
Hi @wangmir , thanks for the question. Unfortunately, we can't provide the exact reason for discouraging NDIS DMA on ARM/ARM64 processors. This was a request from the NDIS team to steer driver writers in the direction of WDF DMA or WDM DMA for ARM, so that's what we recommend.

If you're having memory management issues in your driver, I'd first advise following the provided links to see if WDF DMA or WDM DMA can help solve your problem. If you're experiencing issues with development, since we're only equipped to assist with documentation questions I'll recommend checking out these forums:

[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

The community there is quite responsive and would be better equipped to help you with your problem. Best of luck, and thanks again.
