### ISSUE TITLE
Sr Dev Support Escalation Eng

### ISSUE THREAD

**Issue by Ron-Hu** [MicrosoftDocs/windows-driver-docs#855]
User-mode applications or kernel-mode drivers can access a top-level collection by opening its PDO and using the HIDClass support routines and the HID class driver IOCTLs.

Two URLs or links are in the above sentence on the page.  They don't go to their respective spots but to the top generic WDK page.  This is not helpful for me in MS reviewing the documentation or I would think others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8c26c3-6852-e8e9-520d-6e1acbf2f81d
* Version Independent ID: c20b8fff-080d-9798-c236-02d4f8c6dce5
* Content: [Top-Level Collections](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/top-level-collections#feedback)
* Content Source: [windows-driver-docs-pr/hid/top-level-collections.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/top-level-collections.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, Ron.
In the MSDN authoring environment, we had many pages that we added that gave short descriptions of groups of DDIs. In the DOCS system, we cannot mix conceptual topics in with the structured ref topics, so we moved those conceptual pages into the parent topics for the technologies, like [HID Minidriver IOCTLs](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_hid/#hid-minidriver-ioctls). It was a manual process to move them, and we tried to make sure that all links were also changed, but we may have missed some. If you see any more links that go to the portal page, instead of where they should, please create issues. We'll take it from there. Thanks!
