### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#886]
Provide an usage example for each command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91700cd5-babb-708a-1aa3-04a9ced5661e
* Version Independent ID: 693a536c-6243-2486-310d-2aefd1a97467
* Content: [dds, dps, dqs (Display Words and Symbols)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dds--dps--dqs--display-words-and-symbols-)
* Content Source: [windows-driver-docs-pr/debugger/dds--dps--dqs--display-words-and-symbols-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/dds--dps--dqs--display-words-and-symbols-.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Thanks for this issue and additional examples would be good. Right now I'm working on the new stop codes that we have not documented at all, so not sure when I will be able to work on this.

**Comment by DOMARS** [comment]
@LuigiBruno - The idea of adding more samples to this command is a good one. But sadly because of doc team resource constraints, this does not look like something we will be able to do. The community is welcome to create more examples for this command and submit a PR. Thanks for your interest in improving the debugger docs.
